### ISSUE TITLE
Get addons channel right before emitting

### ISSUE THREAD

**Issue by mgtitimoli** [tuchk4/storybook-readme#10]
Hey there!

I am trying to use the extension in **React Native**, but I'm getting this error:

![image](https://cloud.githubusercontent.com/assets/4404683/23144133/5f0599e6-f7a4-11e6-8ad3-c2f2cc3a25c8.png)

After digging a while, I noticed the channel is being cached [outside](https://github.com/tuchk4/storybook-readme/blob/master/src/with-readme.js#L5) the main function.

I set some conditional breakpoints that allowed me to try solving the issue by getting the channel right before emitting, and indeed this did the magic.

This issue is happening due the fact that the channel is set in the [provider constructor](https://github.com/storybooks/react-native-storybook/blob/master/src/manager/provider.js#L13) and this happens after the extension is parsed, so at that time `addons.getChannel()` returns **null**.

I was wondering if you find anything wrong with this solution, and if not, I would like to submit a PR with this fix.

Thanks!

**Comment by tuchk4** [comment]
@mgtitimoli Hi! Thanks for reporting.

I dont see any problems in this solution. It should work. 
I will be glad to merge your PR.

**Comment by mgtitimoli** [comment]
Hi @tuchk4,

Almost at the speed of light :slightly_smiling_face:...

[PR](https://github.com/tuchk4/storybook-readme/pull/11)

Thanks to you!

**Comment by tuchk4** [comment]
merged abd published
try version `1.3.1`

**Comment by mgtitimoli** [comment]
Marvelous :sparkles:, thanks @tuchk4!

**Comment by mgtitimoli** [comment]
Could it be you forgot to push the version change to [package.json](https://github.com/tuchk4/storybook-readme/blob/master/package.json#L3)?

(In addition, when you are fixing that, you could correct this [little typo](https://github.com/tuchk4/storybook-readme/blob/master/package.json#L4)) :slightly_smiling_face:

**Comment by tuchk4** [comment]
@mgtitimoli yea. I just forgot to push local changes.
Everything is OK with `1.3.1`?

**Comment by mgtitimoli** [comment]
Yeah, it's working great @tuchk4, thanks!

Ping me if someday you need any help with the project.

**Comment by tuchk4** [comment]
OK 

Thank you 👍
