### ISSUE TITLE
Inconsistent HTML generated for JSX code blocks

### ISSUE THREAD

**Issue by andyfryy** [tuchk4/storybook-readme#101]
Hi there, 

Firstly, awesome storybook addon! I've been using it extensively for documentation purposes for a while. 

I'm trying to get `doc` to work, and while it's mostly generating the correct HTML from my markdown file, I'm getting some inconsistent behavior in terms of newlines.

The markup I'm trying to render is the following: 

```jsx
import Card from './Card';

const Body = <div>Define your body/footer outside of the card</div>

const Footer = (props) => {
  return (
    <div>Now you can pass them as {props.type} to your card</div>
  )
}

const ParentContainer = () => {
  return (
    <Card
      body={Body}
      footer={<Footer type="props" />} />
  )
}
```

And the generated HTML looks like this: 

 
![screen shot 2018-10-25 at 9 53 41 am](https://user-images.githubusercontent.com/37874378/47505309-efa46a80-d83b-11e8-8441-f24a70385d8c.png)

So you can see that it gets the newlines and tabbing correct for the first few lines, but the last few lines aren't. 

Thank you for your help! I can provide more examples or context if needed.

**Comment by andyfryy** [comment]
I should also note that this markdown IS formatted correctly when I use `withReadme`.

**Comment by tuchk4** [comment]
@andyfryy Could you please show usage example? 

I can not reproduce this :(

![image](https://user-images.githubusercontent.com/5140611/47506127-27310800-d878-11e8-84c7-dac1825f3bd5.png)

**Comment by andyfryy** [comment]
Thank you for the super quick turnaround, here's my story: 

```jsx
import React from 'react';
import { storiesOf } from '@storybook/react';
import { doc } from 'storybook-readme';
import Marked from 'storybook-readme/components/Marked';
import cardReadme from '../src/Card/readme.md';

storiesOf('Card', module).add('using normal doc component', doc(cardReadme));

storiesOf('Card', module).add('using Marked component', () => {
  return (
    <div>
      <Marked md={cardReadme} />
    </div>
  );
});
```

and here's my markdown file: 

```md
### Passing elements to the body and footer

```jsx
import Card from './Card';

const Body = <div>Define your body/footer outside of the card</div>

const Footer = (props) => {
  return (
    <div>Now you can pass them as {props.type} to your card</div>
  )
}

const ParentContainer = () => {
  return (
    <Card
      body={Body}
      footer={<Footer type="props" />} />
  )
}
```

```

**Comment by andyfryy** [comment]
In terms of versions: 

@storybook/react@3.4.11
storybook-readme@4.0.2
react@16.4.1

**Comment by tuchk4** [comment]
Could you please show webpack config?

**Comment by andyfryy** [comment]
Hey @tuchk4, got this figured out. I updated to Storybook 4 and Webpack 4, and the issue went away. Not sure whether it was Storybook or Webpack that was causing the issue (or whether it was something else). But at any rate: resolved.
