### ISSUE TITLE
Some part of markup not rendering after updating `storybook-readme` to 4.0.0

### ISSUE THREAD

**Issue by MansoorBashaBellary** [tuchk4/storybook-readme#103]
I have my `README.md` file this way:

`
```javascript
import Dialog from 'dialog';
import 'dialog.css';

export default {
  name: 'your-component',
  components: { Dialog },
  template: `
    <dialog>
      <template slot="reference" slot-scope="{ triggerAttrs, triggerListeners }">
        <button v-bind="triggerAttrs" v-on="triggerListeners">
          Trigger
        </button>
      </template>

      <p> Dialog example content</p>
    </dialog >
  `
};
```
`

On loading this `README.md` file in my `storybooks` like:

`
import { withReadme } from 'storybook-readme';
import README from './README.md';

storiesOf(...)
.addDecorator(withReadme(README))
`

In the README Panel of the storybooks, only a part of `html` is getting escaped. This issue is present after updating `storybook-readme` to 4.0.0.

Screenshot of the issue is:

<img width="519" alt="screen shot 2018-11-14 at 12 30 20 pm" src="https://user-images.githubusercontent.com/42977064/48500576-2f41ef00-e809-11e8-9488-c261e00cc306.png">

**Comment by tuchk4** [comment]
Going to investigate this issue tomorrow

**Comment by tuchk4** [comment]
@MansoorBashaBellary cant reproduce. If still actual will be nice if you publish repo with issue reproduction.

**Comment by MansoorBashaBellary** [comment]
Thanks @tuchk4. Issue is not reproducible any more. Closing this issue.
