### ISSUE TITLE
Wrong argument error thrown when running jest storyshot

### ISSUE THREAD

**Issue by sumboxcar182** [tuchk4/storybook-readme#104]
Hello!

I've been trying to get this project to work with storyshots and i followed the steps with #52 where i am adding the markdown loader and babel-jest to our jest config. However when i do that, I get an error when running a storyshot with the error "wrong arguments" 

The way i'm doing things right now is something like 
```
import readme from './README.md'

const stories = storiesOf('Story name', module);
stories.addDecorator(withReadme(readme));
```

With my typings set up to handle the readme import like
```
declare module "*.md" {
    const value: string;
    export default value;
}
```

When running the storybook ui everything does work.

Also while debugging the storyshot test, i'm finding that the readme import does have the markdown text in it, but when the function is called, it is getting an undefined parameter, which is a little odd.

I think these are all the packages that would impact this, but please let me know if you need anything else!

```
babel-jest: 23.6.0
storybook-readme: 4.0.2
@storybook: 4.0.7 (all are up to date)
markdown-loader-jest: 0.11.1
```

Again if there's anything else i can provide to help out i have no problem doing that, as this feature is amazing and i'd like to get this into our storybook!

**Comment by tuchk4** [comment]
Going to investigate this issue tomorrow

**Comment by tuchk4** [comment]
Close this for now.
If face it again reopen or create new issue. Will be cool if provided repo with reproduction.
