### ISSUE TITLE
Markdown does not load if initial focus is on another addon tab

### ISSUE THREAD

**Issue by Pessimistress** [tuchk4/storybook-readme#105]
Steps to reproduce:

- Go to [demo](https://tuchk4.github.io/storybook-readme/?selectedKind=With%20Docs%20and%20Readme&selectedStory=Button&full=0&addons=1&stories=1&panelRight=1&addonPanel=storybooks%2Fstorybook-addon-knobs)
- Click on "README"
- Tab shows "README.md was not added"

If I navigate to another story and back with the focus on the "README" tab, the content loads.

**Comment by tuchk4** [comment]
Hi, already have fix for this issue. Going to release at this week

**Comment by semoal** [comment]
@tuchk4 Hi, did you released?

Thanks!

**Comment by bpb27** [comment]
noticing the same issue, checking in on the status. great addon! 🥇

**Comment by ajitbohra** [comment]
noticing same

**Comment by ajitbohra** [comment]
@tuchk4 any update?

**Comment by tuchk4** [comment]
@ajitbohra sorry for late response, have a lot of work. Going to release new version tomorrow.

**Comment by tuchk4** [comment]
released at `4.0.4`

**Comment by semoal** [comment]
I've tested with my project, and works correctly mate. We can close this issue.

**Comment by tuchk4** [comment]
@semoal  nice. sorry for taking so much time :)

**Comment by bpb27** [comment]
fixed for me too. many thanks 🥇 🎉 !

**Comment by tuchk4** [comment]
Close this for now. Reopen or create new if any errors

**Comment by ajitbohra** [comment]
Works as expected, thank you @tuchk4 :tada: :heart:
