### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by semoal** [tuchk4/storybook-readme#106]
I'm seeing a warning on my storybook console on Chrome...

`Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
    in ReadmePanel (created by Tabs)`

I'm using storybook-readme ^4.0.2 & storybook version, ^4.0.12

I'm not sure if it's a issue, but i'm a bit scared of the memory leaks problem... Actually i have like 20 components and it looks ok, but i think in the future can be a problem.

Thanks!

Let's discuss 👍

**Comment by tuchk4** [comment]
Never face such error but possibly fixed at https://github.com/tuchk4/storybook-readme/commit/bd3f8cd960aa423c4218ceb80480c27bc3167e90#r31894807

**Comment by tuchk4** [comment]
possibly released at `4.0.4`

waiting for a feedback

**Comment by semoal** [comment]
Tested for a while, like ten minutes changing views, components, toggling dark theme / light them etc.
And zero errors, looks like your change fixed it. I think we can close, anyways if i see this other time i'll notice you!

Thanks mate for your hard-work, i'll try to fix some features If i get some time available

**Comment by semoal** [comment]
Tested for a while, like ten minutes changing views, components, toggling dark theme / light them etc.
And zero errors, looks like your change fixed it. I think we can close, anyways if i see this other time i'll notice you!

Thanks mate for your hard-work, i'll try to fix some features If i get some time available
