### ISSUE TITLE
Please add LICENSE files to your packages :)

### ISSUE THREAD

**Issue by benwiley4000** [tuchk4/storybook-readme#108]
There is no license file in any of the packages, nor is there one at the top level of the repository. It would be ideal to have the license added to each package (I think newer versions of Lerna do this automatically on publish). This is usually based on the LICENSE at the top of the repo. Having a license file will help users audit their dependencies. Thanks!

**Comment by tuchk4** [comment]
Thanks for request.

I am going to complete and finish all bugs and feature requests at the
start of next week.

**Comment by tuchk4** [comment]
released at `4.0.4`

**Comment by benwiley4000** [comment]
Thanks!!
