### ISSUE TITLE
Allow <!-- CODE --> and <!-- PROP_STABLE --> snippets (React)

### ISSUE THREAD

**Issue by ChristiaanScheermeijer** [tuchk4/storybook-readme#113]
First of all, thank you for this addon!

Before I'd installed this addon, I was playing with `@storybook/addon-info`. I really liked the autogenerated code and props table snippet from this addon.

So I was thinking, it would be really cool if we could do something like this in the README.md:

```md
# Avatar

### Usage

This code is autogenerated based on the code in the `storiesOff#add` function:

<!-- CODE -->

### Preview

<!-- STORY -->

### Properties

A Markdown table with all props generated from the defaultProps and propTypes:

<!-- PROPS_TABLE -->
```

**Comment by tuchk4** [comment]
@ChristiaanScheermeijer Nice idea!
I will definitely do it in next release. Planning to do it at the start of next week

**Comment by tuchk4** [comment]
Will be released with https://github.com/tuchk4/storybook-readme/issues/118

**Comment by tuchk4** [comment]
@ChristiaanScheermeijer release at `storybook-readme@5.0.0-alpha.150`

```md
Here is docs

Here is Story
<!-- STORY -->

Here is Props table
<!-- PROPS -->

Here is docs after props table
```

**Comment by tuchk4** [comment]
feature added at `5.0.0`

**Comment by deini** [comment]
@tuchk4 Are there any plans to support `<!-- CODE -->` so that we can handle the use case the description of this issue mentions?
