### ISSUE TITLE
Styling not inherited with Marked component

### ISSUE THREAD

**Issue by rossmoody** [tuchk4/storybook-readme#114]
A little new to this so unsure if bug or intended behavior but I really like the `Marked` method of documenting my story. My issue is tables are coming in without style unless I import `withDocs` in some way and do a workaround. I think it would be nice if the ReadMe styling was inherited with the `Marked` component import.

## Scenario 1
I import `Marked` and embed my `PropTable` markdown file inline via `<Marked md={PropTable} />`. The table looks like this:

![image](https://user-images.githubusercontent.com/29072694/53115519-46286980-34fb-11e9-9955-e6b16936144d.png)

## Workaround Scenario 2
~I import `Marked` and `withDocs`. I add the code `withDocs.addFooterDocs(PropTable)` and keep my `PropTable` markdown file inline in the same place as scenario 1. It renders correctly:~ That was a bug. Doesn't work dependably. An easier workaround is to `import 'storybook-readme/styles/github-markdown-css.js'` at the top of the file. 
 
![image](https://user-images.githubusercontent.com/29072694/53115705-bd5dfd80-34fb-11e9-9a91-697e13161469.png)

**Comment by tuchk4** [comment]
Will be fixed with https://github.com/tuchk4/storybook-readme/issues/118

**Comment by tuchk4** [comment]
Should be fixed in `5.0.0`

**Comment by tuchk4** [comment]
Please test it and open new issue if faced it again.
NOTE that this feature work only for React storybook
