### ISSUE TITLE
Markdown jsx code block weirdly parsed

### ISSUE THREAD

**Issue by PatrickChevalierADSK** [tuchk4/storybook-readme#115]
Hi,

first thank you for this awesome addon it is a great addition to our storybook!

We have an issue where a jsx code block is wrongly parsed and components like `<Button>` are rendered as `&lt;Button&gt;&lt;/Button&gt;`. 

Here are some screenshots : 
![image](https://user-images.githubusercontent.com/34252595/53271790-79b2f180-36bd-11e9-82cb-9b61b9f01e22.png)
![image](https://user-images.githubusercontent.com/34252595/53271812-83d4f000-36bd-11e9-96c2-82056d567f69.png)

Obviously the real life case where this is happening consist of a way bigger block of code but I stripped it down to the least number of lines while still having the issue. I can provide the real life example on demand.

Are you able to help with this?

Thanks you very much!

Here is the code block: 

## Overview

```jsx


    return (
      <Button></Button>
    );


```

**Comment by tuchk4** [comment]
duplicate #112
