### ISSUE TITLE
Markdown backticks render as block elements

### ISSUE THREAD

**Issue by bzeffren** [tuchk4/storybook-readme#12]
First off, thanks for the great work on this add-on. We are using it a ton, and it's very helpful to the whole team 😄 

I've just noticed that in the current version, markdown backticks are being rendered as `display: block` by `highlight.js` which is causing some layout problems. 

<img width="385" alt="image" src="https://cloud.githubusercontent.com/assets/2984125/23281297/56cb0500-f9e2-11e6-9d22-432bb86e458e.png">
<img width="375" alt="image" src="https://cloud.githubusercontent.com/assets/2984125/23281330/76e03cca-f9e2-11e6-8efb-7adb1aa6f2bd.png">

When I fix my version of `storybook-readme` to `1.2.0` the problem seems to go away, along with the `hljs` classes.

<img width="583" alt="image" src="https://cloud.githubusercontent.com/assets/2984125/23281759/3d0dac88-f9e4-11e6-8d38-25a55e65695b.png">

**Comment by tuchk4** [comment]
How can I reproduce this? Could you please provide markdown with layout problems?

**Comment by juliuxu** [comment]
Sure, try this:

    Here I use a `backtick`, it should not be treated as a code block.
    ```javascript
    console.log("This is a normal code block");
    ```

It should look like this:
![screenshot from 2017-03-02 15-28-07](https://cloud.githubusercontent.com/assets/244257/23511273/d9f4556a-ff5c-11e6-8826-10eefb3b18ef.png)

But ends up looking like this:
![screenshot from 2017-03-02 15-23-26](https://cloud.githubusercontent.com/assets/244257/23511057/36080f6e-ff5c-11e6-95d4-d96732df13d0.png)

All code blocks are wrapped with `<pre>` before ` <code>` whereas backticks are not.
![screenshot from 2017-03-02 15-19-43](https://cloud.githubusercontent.com/assets/244257/23511027/192c6c50-ff5c-11e6-8da3-ba0b9a42c4f8.png)

Changing the highlight selector back to look for `pre code` will fix this.

**Comment by tuchk4** [comment]
yep. got it.

**Comment by tuchk4** [comment]
Merged and released. Try `v1.3.2`
