### ISSUE TITLE
text-align: center with readme decorator

### ISSUE THREAD

**Issue by b0g3r** [tuchk4/storybook-readme#122]
My component inherit text-align from storybook-readme decorator and it brokes my component style :(
![image](https://user-images.githubusercontent.com/19777948/54082714-123aaa00-432b-11e9-8529-8f8d5488268a.png)

**Comment by tuchk4** [comment]
Will change default wrapper for story at next release #118

**Comment by tuchk4** [comment]
Changed `StoryPreview` component https://github.com/tuchk4/storybook-readme/blob/master/packages/storybook-readme/src/components/Preview/StoryPreview.js

released at storybook-readme@5.0.0-alpha.150
But note that right now there are breaking changes with API. I wrote about here #118 (comment).
Big chance that at release I will add support for previous api so no needs to change existing storybooks.

**Comment by tuchk4** [comment]
fixed in `5.0.0`

Also in is possible to override story decorator to set your own styles.
