### ISSUE TITLE
5.0.0-alpha packages have Dev machine paths

### ISSUE THREAD

**Issue by Zyzle** [tuchk4/storybook-readme#126]
Right now it seems like bringing down either 5.0.0-alpha.149 or 150 from yarn results in files that contain absolute paths on developer machines:

Example from `my-project/node_modules/storybook-readme/index.js`:

```js
import _objectSpread from "/Users/valeriis/Develop/Github/storybook-readme/node_modules/babel-preset-react-app/node_modules/@babel/runtime/helpers/esm/objectSpread";
```

A similar thing can be found in a few places in the installed node module

**Comment by tuchk4** [comment]
Will fix with #125

**Comment by JamesIves** [comment]
Is there an ETA on #125? Would love to roll out SB5 asap.

**Comment by tuchk4** [comment]
@JamesIves few hours for this fix

**Comment by tuchk4** [comment]
This helped https://github.com/facebook/create-react-app/issues/5443#issuecomment-430188464

**Comment by tuchk4** [comment]
@JamesIves @Zyzle 
Please try `storybook-readme@5.0.0-alpha.158`

**Comment by Zyzle** [comment]
@tuchk4 Apologies, I thought I'd replied to this yesterday. Yes the 159 update has resolved this issue.

**Comment by tuchk4** [comment]
BTW 5.0.0 released
