### ISSUE TITLE
<!--- PROPS --> not caught with styled-components HOC

### ISSUE THREAD

**Issue by semoal** [tuchk4/storybook-readme#131]
Hi!!

I'm using on some components withTheme() HOC from styled-components, actually this addon can't get the props table working with it.

```js 
export default withTheme(TextField);
```
![Captura de pantalla 2019-03-16 a las 19 18 38](https://user-images.githubusercontent.com/22656541/54479736-5264c580-4820-11e9-9179-fffa0322a139.png)

```js 
export default TextField;
```
![Captura de pantalla 2019-03-16 a las 19 19 08](https://user-images.githubusercontent.com/22656541/54479739-68728600-4820-11e9-98c1-6bb7b65894f0.png)

Thanks!

**Comment by tuchk4** [comment]
exported component should be with defined `propTypes`.

`withTheme` should copy propTypes automatically..
In other cases use [hoist-non-react-statics](https://www.npmjs.com/package/hoist-non-react-statics)

**Comment by semoal** [comment]
Actually I’m doing the first one and it doesn’t work mate.

**Comment by tuchk4** [comment]
I made some local tests and everything is ok with `"styled-components": "^4.1.3"`

**Comment by semoal** [comment]
I’m out home but I guess it’s yours version. Latest stable.

The only difference I remember(later I’ll check it better), is I’m using default props too but damn it the code is almost the same. (All  speaking from memory)

**Comment by tuchk4** [comment]
released example https://tuchk4.github.io/storybook-readme/?path=/story/propstable--button with `withTheme` 
Here is sources https://github.com/tuchk4/storybook-readme/blob/master/packages/example-react/components/Button/index.js


Please try `storybook-readme@5.0.0` and if faced again would be perfect to push repo with reproduction the issue.

**Comment by semoal** [comment]
Valerii here you have a branch example:
https://github.com/semoal/storybook-readme/tree/bug-hoc-sc
https://github.com/semoal/storybook-readme/blob/bug-hoc-sc/packages/example-react/components/Button/index.js

**Comment by semoal** [comment]
Valerii have you tried my proposal?

**Comment by tuchk4** [comment]
I would like to link this issue with #137
