### ISSUE TITLE
vue + JSX issue has resurfaced in v5.0

### ISSUE THREAD

**Issue by Aaron-Pool** [tuchk4/storybook-readme#138]
Addressed about this time last year with issue #49 the `object is not extensible` problem seems to have resurfaced when I moved to `v5.0`. In fact, it looks like there aren't any vue + jsx examples that made the jump to `v5.0`.

Thoughts?

**Edit:** I found the issue. Vue commands are now imported from a different location, and this isn't anywhere in the docs. I submitted a docs PR to make this clear.

**Comment by tuchk4** [comment]
Going to investigate this issue this week and fix with `5.0.2`

**Comment by tuchk4** [comment]
@Aaron-Pool Thanks for clarifying README for vue users
