### ISSUE TITLE
Use extend in webpack.config.js

### ISSUE THREAD

**Issue by pbit** [tuchk4/storybook-readme#14]
Hi and thanks for this addon.

I had some trouble using the webpack.config.js from the README.
The given example overrides the defaults so you have to repeat everything.

The solution was to use the extend feature:

```
npm install --save-dev storybook-readme raw-loader
```

```javascript
const path = require('path')
const genDefaultConfig = require('@kadira/storybook/dist/server/config/defaults/webpack.config.js')

module.exports = function (storybookBaseConfig, configType) {
    const config = genDefaultConfig(storybookBaseConfig, configType)
    config.module.loaders.unshift({
        test: /\.md$/,
        loader: require.resolve('raw-loader'),
        include: path.resolve(__dirname, '../src')
    })

    return config
}
```

**Comment by tuchk4** [comment]
I am going to remove any additional configuration for this addon.
I hope after nearest release will resolve all such problems

**Comment by pbit** [comment]
Definitely a better solution ;)

**Comment by tuchk4** [comment]
@pbit I have published `storybook-readme@2.0.0` without additional webpack configuration. Only for `*.md` files

```js
module.exports = {
  module: {
    loaders: [{
      test: /\.md$/,
      loader: "raw"
    }]
  }
};
```

**Comment by tuchk4** [comment]
closed issue.

Please file issue if you face troubles in `2.0.0`

**Comment by pbit** [comment]
Great, was not a real issue but just a hint how to use this without breakin stuff...
