### ISSUE TITLE
Markdown Github Pre/Code Style

### ISSUE THREAD

**Issue by callerc1** [tuchk4/storybook-readme#141]
Hello 👋. I just upgraded to v5.0.1 any reason why these styles are commented?

https://github.com/tuchk4/storybook-readme/blob/master/packages/storybook-readme/src/styles/githubMarkdownCss.js#L343

**Comment by tuchk4** [comment]
@callerc1 Actually this may did by mistake. 

Going to investigate

**Comment by tuchk4** [comment]
Uncommented all code that does not affect on code theme

**Comment by tuchk4** [comment]
published 5.0.2

**Comment by jchiem** [comment]
seems to still be commented out in the npm version you get when you download storybook-readme@5.0.5 
![Screenshot from 2019-07-22 12-28-40](https://user-images.githubusercontent.com/3385622/61625962-49777b00-ac7c-11e9-9f8c-f99abd902520.png)
![Screenshot from 2019-07-22 12-28-27](https://user-images.githubusercontent.com/3385622/61625964-49777b00-ac7c-11e9-8eab-96c857c1c108.png)
