### ISSUE TITLE
PropTypes displaying as `[Object object]`

### ISSUE THREAD

**Issue by fauxparse** [tuchk4/storybook-readme#143]
The `type` column of my PropTypes table (for a React component) is displaying all types as `[Object object]`. Perhaps something has changed or is not set up correctly, because 

To fix this, I had to hack the `propsFromDocgen` function as follows:

```
propType: propType.name || propType,
```

Doing a bit of digging, I found that in my particular case, `propTypes` is ending up with an object rather than a plain string.

Am I doing something wrong?

**Comment by tuchk4** [comment]
Thanks for reporting.
I would like to link this issue with #137 

Going to fix both as soon as possible

**Comment by Zyzle** [comment]
@tuchk4 is there any chance you could add the above from @fauxparse as a fix for this? It seems proptypes are now always returned as objects from babel-plugin-react-docgen in the most recent versions

**Comment by tuchk4** [comment]
@Zyzle I am going to release new version with this fix at the end of this week.
