### ISSUE TITLE
v5 equivalent of `doc()`?     [question]

### ISSUE THREAD

**Issue by metasean** [tuchk4/storybook-readme#144]
In the 4.x.x version of Storybook-readme there was a `doc()` method, that wasn't attached to an explicit Vue component, e.g. in [storybook-readme/packages/example-vue/stories/withOldApi.js](https://github.com/tuchk4/storybook-readme/blob/master/packages/example-vue/stories/withOldApi.js#L32):
```javascript
storiesOf('Old Api', module).add('doc', doc(ButtonReadme));
```

I'm not seeing an equivalent to `doc()` in v5.x.x.

_Is there one, and if so, can someone point me to an example of it or the documentation for it?_

**Comment by tuchk4** [comment]
Yes, you can use it. Docs about this method are in this [LEGACY_README](https://github.com/tuchk4/storybook-readme/blob/master/LEGACY_README.md).

Think I should move it to main README.

**Comment by metasean** [comment]
@tuchk4 - I'm not looking for how to do it in v4.  I had it working in v4, upgraded to v5, and it no longer works.  

Is the `doc()` api supposed to still be working in v5?  
Or is there a way to generate the same output using the new v5 api?
