### ISSUE TITLE
Unable to customize styles

### ISSUE THREAD

**Issue by joepuzzo** [tuchk4/storybook-readme#145]
In the docs it states the following: 

```
 /**
     * Highlightjs code theme
     * Import theme at _.storybook/config.js_.
     * Full list of theme https://highlightjs.org/static/demo/.
     */
    codeTheme: 'atelier-cave-dark',
```
I try to add this line

`codeTheme: 'atelier-cave-dark',` and nothing changes. 

It describes in the comment to import the theme in the `.storybook/config.js` file yet when i look at your example source code there exists no import.

**Comment by joepuzzo** [comment]
https://github.com/tuchk4/storybook-readme/blob/592b2c9488e94288dfc6021c9a04c1db4df0b82f/packages/example-react/.storybook/config.js <<< From the docs i would expect to see an import here

**Comment by tuchk4** [comment]
Could you please show you `storybook` and `storybook-readme` version.
The example you provided is 100% working.

**Comment by joepuzzo** [comment]
Yup so im using the following versions: 

```
    "storybook-readme": "^5.0.1",
    "@storybook/react": "^5.0.5",
```

And let me elaborate on my question: 

So when i look at your source code https://github.com/tuchk4/storybook-readme/blob/master/packages/example-react/stories/withCustomCodeTheme.js You are correct, your code has the following line 

```
     codeTheme: 'atelier-cave-dark',
```

So therefore after looking at that and reading the docs, its my understanding that if I were do do the same thing as you ( simply add `codeTheme: 'atelier-cave-dark',` to my `addParameters` then my code blocks will get that theme! However, this is not the case. 

My follow up to that was to reference a comment i found in the docs that states `Import theme at _.storybook/config.js_.`. After reading that it made me think, "ok i must be missing something". BUT, then I look in your source code under your `.storybook/config.js` file and there are no imports to any highlight js libs. 

Does this clarify my question. Im just trying to figure out why the styles are not getting applied

**Comment by lonyele** [comment]
@joepuzzo I'm not sure If I understand correctly, but my guess is that
-  you are using `addParameters({ ... })` at `.storybook/config.js` 
- with the code something like as the link you [mentioned](https://github.com/tuchk4/storybook-readme/blob/592b2c9488e94288dfc6021c9a04c1db4df0b82f/packages/example-react/.storybook/config.js) 
```
addParameters({
  name: 'README addon',
  url: 'https://github.com/tuchk4/storybook-readme',
  options: {
    addonPanelInRight: true,
  },
  // options: {
  //   theme: themes.dark,
  // },
});
```
- or like this as the link(https://github.com/tuchk4/storybook-readme/blob/master/packages/example-react/stories/withCustomCodeTheme.js)
```
addParameters({
  readme: {
    codeTheme: 'shades-of-purple',
    // codeTheme: 'atelier-cave-dark',
    content: ButtonReadme,
    sidebar: ButtonUsage,
  },
})
```

I think documentation needs to be udpated for more clarity. It shouldn't work if you used `addParameters()` at `./storybook.config.js` Can you try this setup?
At `./storybook/config.js`, code should be like this. No addParameters here.
```
import { addDecorator, configure } from '@storybook/react';
import { addReadme } from 'storybook-readme';

addDecorator(addReadme);

function loadStories() {
  require('../stories');
}

configure(loadStories, module);
```
and at your stories, you add it such as the [withCustomCodeTheme.js example](https://github.com/tuchk4/storybook-readme/blob/master/packages/example-react/stories/withCustomCodeTheme.js)
```
    
import React from 'react';
import { storiesOf } from '@storybook/react';

storiesOf('Whatever name for your story', module)
  .addParameters({
    readme: {
      codeTheme: 'atelier-cave-dark',
      content: 'Your Readme for content',
      sidebar: 'Your REadme for sidebar',
    },
  })
  .add('Is it working??', () => <div>'Hope it is working now'</div>);
```
I hope it is working now. The example you [mentioned](https://github.com/tuchk4/storybook-readme/blob/592b2c9488e94288dfc6021c9a04c1db4df0b82f/packages/example-react/.storybook/config.js) needs to be updated. 

@tuchk4 Do you mind If I change some documentations and examples? I tested using `addParameters()` at `stories.config.js` and It actually does work for global configuration.

**Comment by joepuzzo** [comment]
@lonyele I am doing literally what you have above ^^^^ and it does not work? 

```
const params = {
  readme: {
    /**
     * Highlightjs code theme
     * Import theme at _.storybook/config.js_.
     * Full list of theme https://highlightjs.org/static/demo/.
     */
    codeTheme: 'atelier-cave-dark',
  },
};

storiesOf('Introduction', module)
  .addParameters(params)
  .add('Getting Started', Intro);
```

**Comment by joepuzzo** [comment]
Opps my bad you were right!!! it was this I was missing! `addDecorator(addReadme);`

**Comment by tuchk4** [comment]
@lonyele Thank for clarification! Documentation should be updated. 

Global configuration is not working correctly because any new parameters at `storiesOf(...).addParameters(...` will not be merged with global params but overridden.

**Comment by lonyele** [comment]
@tuchk4 Isn't that what is intended for? I thought of configuring global for general cases, and the user can override specific story if it is needed

**Comment by tuchk4** [comment]
@lonyele yes. But usually users set README at each story and thats why it overrides all default settings

**Comment by tuchk4** [comment]
@lonyele hm. Made some tests now and see that configs are merged (global `addParameters` and stories `addParameters`).

Few weeks ago it was the other way around. Maybe some changes in storybook.. Going to check it a bit later.

Anyway now docs updated (thanks to @lonyele ) and everything works
