### ISSUE TITLE
Empty <div> with margins is added for other addons

### ISSUE THREAD

**Issue by andrei-ilyukovich** [tuchk4/storybook-readme#149]
Adding storybook-readme addon causes appearing unwanted empty `<div>` element in structure of other addons (like knobs, actions etc.) which causes adding unnecessary vertical scroll. Please see attached images for more details:

![image](https://user-images.githubusercontent.com/6919053/55639288-b3edd380-57d1-11e9-9da1-e27112f24ecf.png)

![image](https://user-images.githubusercontent.com/6919053/55639313-c0722c00-57d1-11e9-97d6-743c1f11fcc9.png)

**Comment by tuchk4** [comment]
I made fix but not sure it is correct.
I don't remember why initially I made wrapper [outside](https://github.com/tuchk4/storybook-readme/commit/bfcaa7c57ef87a55902fd7b089481a2fa2451c27#diff-b6b2b81b51c401c7bb23f5599f217efeL20) but not directly at [ReadmeSidebar](https://github.com/tuchk4/storybook-readme/commit/bfcaa7c57ef87a55902fd7b089481a2fa2451c27#diff-d7bf9ecae083996c36b6f4fc48469306R66)

**Comment by tuchk4** [comment]
published 5.0.2
