### ISSUE TITLE
When Using Backticks in ".md" Files - Unicode Characters are Broken on the Page

### ISSUE THREAD

**Issue by adamhenson** [tuchk4/storybook-readme#16]
How to reproduce:

I reproduced this in the demo, by changing any of the bolded words in readme.md files like this `**emphasized words**` with this `` `emphasized words` ``. Backticks are commonly used by developers in documentation.

I've identified the issue, which relates to the handling of unicode in CSS content stored in a JavaScript template string. I have a very simple solution and will submit a PR shortly.

**Comment by adamhenson** [comment]
<img width="1688" alt="screen shot 2017-03-25 at 11 52 45 am" src="https://cloud.githubusercontent.com/assets/747743/24324222/c4164b32-1158-11e7-8b54-06a4aac26e38.png">

**Comment by tuchk4** [comment]
Check `v2.0.2`
