### ISSUE TITLE
issue with webpack 4.30.0

### ISSUE THREAD

**Issue by wonskarol** [tuchk4/storybook-readme#164]
Storybook `@storybook/react v5.0.11` uses webpack 4.30.0 and it produces error inside `storybook-readme`:
```
ERROR in ./node_modules/storybook-readme/styles/codeThemeCss.js 28:2
Module parse failed: 'import' and 'export' may only appear at the top level (28:2)
You may need an appropriate loader to handle this file type.
| 
| 
>   import("./prismCodeThemes/".concat(codeTheme, ".css.js")).then(function (t) {
|     insert({
|       styles: t.default
 @ ./node_modules/storybook-readme/components/ReadmeContent/index.js 36:43-79
 @ ./node_modules/storybook-readme/index.js
 @ ./node_modules/@collibra/storybook/.storybook/config.js
 @ multi ./node_modules/@storybook/core/dist/server/common/polyfills.js ./node_modules/@storybook/core/dist/server/preview/globals.js ./node_modules/@collibra/storybook/.storybook/config.js ./node_modules/webpack-hot-middleware/client.js?reload=true
```
This is caused by https://github.com/webpack/webpack/issues/8656. 
Any suggestions how to fix it without locking webpack version to 4.28?
This is pretty ugly, because storybook is not starting.

**Comment by tuchk4** [comment]
This is webpack issue so we can do nothing with it. 
There is one solution is to bundle all code theme CSS and insert just used in runtime.

Seems we should publish this fix and remove when webpack fix that issue.

**Comment by tuchk4** [comment]
Close this issue because of duplicate.

All discussing are at #134 issue.
