### ISSUE TITLE
Javascript rendering around readme

### ISSUE THREAD

**Issue by TCiobanu** [tuchk4/storybook-readme#168]
Has anybody seen anything like this? I've got javascript coming in before and after the readme is loaded in content or the sidebar.

<img width="697" alt="Screen Shot 2019-05-07 at 3 54 51 PM" src="https://user-images.githubusercontent.com/45999695/57328846-8782eb00-70e0-11e9-8d0b-0d99efc222de.png">

**Comment by tuchk4** [comment]
Could you please show used version os storybook and storybook-readme and example of your story with issue

**Comment by TCiobanu** [comment]
Sure thing.

I'm using:

"@storybook/addon-a11y": "^5.0.11",
"@storybook/addon-actions": "^5.0.11",
"@storybook/addon-info": "^5.0.11",
"@storybook/addon-knobs": "^5.0.11",
"@storybook/addon-viewport": "^5.0.11",
"@storybook/react": "^5.0.11",
"storybook-readme": "^5.0.3",

And here's what the story looks like:

```
import React from 'react';
import { Provider } from 'react-redux';
import { storiesOf } from '@storybook/react';
import { action } from '@storybook/addon-actions';
import { withKnobs, text } from '@storybook/addon-knobs/react';

// App
import { store as RootStore } from 'Root';
import ReadMe from '../Readme.md';
import Button from '../index';


const stories = storiesOf('Button', module);
stories.addDecorator(withKnobs);
stories.addDecorator(story => <Provider store={RootStore}>{story()}</Provider>);
stories.addParameters({
    readme: {
        sidebar: ReadMe,
    },
});

stories.add('with text', () => (
    <Button
        content="hello"
        className="button"
        onClick={action('clicked')}
    />
));

stories.add('as dynamic text', () => {
    const buttonText = text('Button Text', 'Change in knobs to change text here');
    return (
        <Button
            content={buttonText}
            className="button"
            onClick={action('clicked')}
        />
    );
});
```

**Comment by tuchk4** [comment]
Show please this `import ReadMe from '../Readme.md';` file

**Comment by TCiobanu** [comment]
It automatically formats it when I paste it in here.

# Button Component
` A clickable button component` 

| Parameter        | Type           | Description  |
| ------------- |:-------------:| -----:|
| content     | String | The text of the button | 
| srcontent | String | The screen reader content| 
| span | [object]| Additional span tag if need| 
| noDefaultStyle | Boolean | Do not use default Style |
| className | String | Additional button classes| 
| data | [object] | Data attributes like 'ana', 'meta', 'prefix'. | 
| disabled | Boolean | Disable the button (no click events) | 
| id | String | ID of the button | 
| form | String | The form the button belongs to | 
| type | String | The use of the button like 'Submit', 'Button' | 
| title | String | The tooltip title | 
| href | String | The URL routed to on click |
| target | String | Specifies where to open the linked document (i.e. '_blank')|

**Comment by tuchk4** [comment]
FYI:  Ive updated your comment. just wrap md content with ```

**Comment by TCiobanu** [comment]
I think the extra text is coming from react-markdown-loader but I haven't been able to track down how it happens.

**Comment by TCiobanu** [comment]
The issue was fixed by removing
```
{
    test: /\.md$/,
    loader: 'react-markdown-loader'
},
```
from my storybook's webpack config.

Thanks for the help!
