### ISSUE TITLE
8px margin causes double scrollbars in Storybook 5.1

### ISSUE THREAD

**Issue by haakemon** [tuchk4/storybook-readme#174]
Something changed in Storybook 5.1, and they added :first-child selector which will add overflow: auto to the div with 8px margin. This causes double scrollbars to appear if the readme is very long.

Why is this div nescessary, could it just be dropped? Changing it to padding would also work I guess.

![vivaldi_2019-06-06_11-30-41](https://user-images.githubusercontent.com/2082481/59023007-1fdecd80-884f-11e9-8d2f-2d8fa3abf308.png)

**Comment by tuchk4** [comment]
fixed in `5.0.4`
