### ISSUE TITLE
Cant read MD files?

### ISSUE THREAD

**Issue by eduardoinnorway** [tuchk4/storybook-readme#18]
Follow all the instructions to the last details and I get:

ERROR in ./components/Button/README.md
Module parse failed: /Users/myname/IdeaProjects/storybooktest/components/Button/README.md Unexpected token (1:5)
You may need an appropriate loader to handle this file type.

**Comment by tuchk4** [comment]
@eduardoinnorway Sorry for late response. For some reason I missed this issue :(

Seems you your webpack loader for **.md* files (raw-loader) is  configured incorrectly.

**Comment by moimikey** [comment]
and also if you are already doing that, don't `exclude: /node_modules/`

**Comment by gaurav5430** [comment]
If you are overriding the default webpack config, you might have to include and configure the raw loader separately
