### ISSUE TITLE
32px margin added to page when only used in sidebar

### ISSUE THREAD

**Issue by tysonmatanich** [tuchk4/storybook-readme#181]
When `content` isn't enabled (readme only in sidebar) storybook-readme still wraps the story in the following HTML. The main issue with this is that it adds a `32px` top and bottom margin to the page.

```html
<div class="storybook-readme-story"><div style="margin: 32px 0px;"><div>
   ...
</div></div></div>
```

**Comment by donifer** [comment]
Any workaround for this? Having the same issue.

**Comment by rianbotha** [comment]
Adding this to your storybook config removes the margins:
```
import { configureReadme } from 'storybook-readme';

configureReadme({
  StoryPreview: ({ children }) => children, // Remove margins added by readme container
});
```
