### ISSUE TITLE
Is it supported on React Native Storybook?

### ISSUE THREAD

**Issue by simply-innovative** [tuchk4/storybook-readme#19]
is it supported on rn storybook? if no do you have any plans for the same?

**Comment by tuchk4** [comment]
I never tested it but according to this issue https://github.com/tuchk4/storybook-readme/issues/10 - seems it should work.

**Comment by simply-innovative** [comment]
thanks @tuchk4  for the response. I got it working too by removing below import files:
- highlight-github-css.js
- github-markdown-css.js

markdown.js & readme-container.js are importing these files and if we look closely these files are using windows & <div/>  which apparently not supported by RN

Do you have any plans to remove these imports, because with these it is not working

**Comment by tuchk4** [comment]
I got it.

But I don't know how to fix because I have no experience with React Native.

Any ideas?

**Comment by ndelangen** [comment]
Maybe @danielduan could offer some assistance regarding RN? 

Is this issue related to a solution for this problem?
https://github.com/tuchk4/storybook-readme/issues/39

**Comment by tuchk4** [comment]
@ndelangen  Seems it is because of the way I include CSS code - [github-markdown-css.js](https://github.com/tuchk4/storybook-readme/blob/master/src/components/github-markdown-css.js ) 

```js
const styleNode = document.createElement('style');
styleNode.id = 'github-markdown-css';
styleNode.innerHTML = styles;

document.head.appendChild(styleNode);
```

We can bundle all CSS into one file and then users should import manually at storybook config. But I don't like this case.

**Comment by danielduan** [comment]
I think you guys might be confusing the react-native storybook that displays the stories themselves and the web instance of storybook that handles all the addons and helps control the react-native storybook.

You should be able to get it working in the storybook web helper while running react native.

**Comment by tuchk4** [comment]
Close issue because of inactivity.
Please reopen or create new if still actual.
