### ISSUE TITLE
Avoid using setAddon API

### ISSUE THREAD

**Issue by arunoda** [tuchk4/storybook-readme#2]
I mean this one: 

```
import { setAddon } from '@kadira/storybook';
```

We've deprecated it by removing it from the docs.
Instead, provide this functionality as a React Component or a wrapper function.

**Comment by arunoda** [comment]
Like this:

```
storiesOf('Button', module)
  .add('Default', () => (
    <WithReadme readme={ButtonReadme}>
      <Button onClick={action('clicked')} label="Hello Button"/>
    </WithReadme>
  ))
```

or 

```
storiesOf('Button', module)
  .add('Default', withReadme(ButtonReadme, () => (
    <Button onClick={action('clicked')} label="Hello Button"/>
  )))
```

**Comment by tuchk4** [comment]
@arunoda  done

**Comment by tuchk4** [comment]
```js
storiesOf('Button', module)
  .add('Default', () => (
    <WithReadme readme={ButtonReadme}>
      <Button onClick={action('clicked')} label="Hello Button"/>
    </WithReadme>
  ))
```

**Comment by tuchk4** [comment]
@arunoda 

If *setAddon* method is deprecated how addon will work with each other?

For example i want to add story with README and with info.
Right now I use [. addWithInfo](https://github.com/tuchk4/storybook-readme/blob/master/example/stories/index.js#L14) method that is available because of *setAddon* method.

So after removing *.setAddon* from api I should do something like this?

```js
storiesOf('Button', module)
  .add('Default', withInfo(withReadme(ButtonReadme, () => (
    <Button onClick={action('clicked')} label="Hello Button"/>
  ))))
```

**Comment by arunoda** [comment]
@tuchk4 Actually it allows reusability a lot.
For an let's say we need to use Notes addon with your one.
So you could do this:

```js
storiesOf('Button', module)
  .add('Default', () => (
    <WithReadme readme={ButtonReadme}>
      <WithNotes notes="Here's my note">
        <Button onClick={action('clicked')} label="Hello Button"/>
     </WithNotes>
    </WithReadme>
  ))
```

It looks ugly and you need to write more code.  If so, JS will save you. You could do this.

```js
function AddStory(storyFn, readMe, notes) {
   return (
     <WithReadme readme={readMe}>
       <WithNotes notes={notes}>
         {storyFn()}
      </WithNotes>
     </WithReadme>
   );
} 
```

I think we need to do something for the Info addon.

**Comment by tuchk4** [comment]
@arunoda 

>  If so, JS will save you

yes yes I thought about this

> I think we need to do something for the Info addon.

Maybe something like

```js
const EXCEPT_COMPONENTS = [WithReadme, WithNotes];

function AddStory(storyFn, readMe, notes) {
   return (
     <WithInfo except={EXCEPT_COMPONENTS} readme={readMe}>
       <WithReadme readme={readMe}>
         <WithNotes notes={notes}>
           {storyFn()}
        </WithNotes>
       </WithReadme>
     </WithInfo>
   );
} 
```

---- 

* https://github.com/kadirahq/react-storybook-addon-info/blob/master/src/components/Story.js

```js
Story.propTypes = {
  ...
  except: React.PropTypes.oneOfType([
    React.PropTypes.object,
    React.PropTypes.array,
  ]),
};

Story.defaultProps = {
  ...
  except: [],
};
```

And check "expect" components
* https://github.com/kadirahq/react-storybook-addon-info/blob/master/src/components/Story.js#L202

* https://github.com/kadirahq/react-storybook-addon-info/blob/master/src/components/Node.js#L57

```js
{
  React.Children.map(this.props.children, (root, idx) => {
    if (except.indexOf(root.type) != -1) {
      return null;
    }

    return (
      <Node key={idx} depth={0} node={root} />
    );
  })
}
```
