### ISSUE TITLE
ReDoS vulnerability in `marked` package.

### ISSUE THREAD

**Issue by ankurkaushal** [tuchk4/storybook-readme#203]
Looks like there's a Regular Expression Denial of Service (ReDoS) vulnerability in `marked` package version `0.6.0` according to the advisory here: https://www.npmjs.com/advisories/1076

Upgrading the package should fix it. I can put up a PR to fix that :)

**Comment by tuchk4** [comment]
lock files updated at https://github.com/tuchk4/storybook-readme/commit/2daddf43abc4803fb9a32ef8d05a103a32acbbcf

Thanks

**Comment by ankurkaushal** [comment]
Does it usually take long to publish these to `npm`? I just tried doing `npm audit fix` and it still says this:

```
 1 vulnerability required manual review and could not be updated
```

**Comment by dtesta** [comment]
Still an issue in 5.0.6

**Comment by dtesta** [comment]
New open issue @ #204
