### ISSUE TITLE
Vulnerability in dependency `marked`

### ISSUE THREAD

**Issue by sareh** [tuchk4/storybook-readme#204]
There is a vulnerability in the dependency `marked` that is used in this package: https://github.com/tuchk4/storybook-readme/blob/master/packages/storybook-readme/package.json

https://www.npmjs.com/advisories/1076/versions. 
It is fixed in version 0.7.0

**Comment by tuchk4** [comment]
will publish today later

**Comment by sareh** [comment]
Thank you, @tuchk4.

**Comment by dtesta** [comment]
Looks good in 5.0.8 - thanks @tuchk4!

**Comment by tuchk4** [comment]
@sareh @dtesta released in 5.0.8

@sareh  thanks for PR :)

**Comment by gbluv** [comment]
We are trying to use version 6.0.28 and seeing this vulnerability https://snyk.io/vuln/SNYK-JS-TRIM-1017038
