### ISSUE TITLE
whats plan for releasing 3.0.0?

### ISSUE THREAD

**Issue by pranavrajsinghchauhan** [tuchk4/storybook-readme#21]
can you please share plans for releasing storybook-readme-3.0.0 compatible with storybook-rn-3.x

**Comment by tuchk4** [comment]
@pranavrajsinghchauhan Sure! I am going to release version compatible with v3 in few days :)

**Comment by pranavrajsinghchauhan** [comment]
Thanks @tuchk4 for the quick response, looking forward for the release :)

**Comment by ndelangen** [comment]
We didn't quite make this week for the 3.0.0 release of storybook, but it looks like it could be on monday!

It's just release-notes matters now..

**Comment by doctyper** [comment]
@ndelangen Sorry to bug, do you still plan on publishing a release this week?

**Comment by mworkr** [comment]
Hi all,

Just to clarify: storybook3.0.0 as been released already.  

I have this working find with 3.0.0, but not the current master -- only a branch I edited locally.

Not done enough digging--but I suspect the reason is that /register /with-readme (rather than src/register and src/with-readme) have dependencies on the old storybook but are not included in master as they are hidden behind .gitignore.  I might be misunderstanding something, though.

**Comment by ndelangen** [comment]
Storybook `3.0.0` has been released! Please follow our migration guide to get this addon to work with the new version: https://github.com/storybooks/storybook/blob/master/MIGRATION.md

If you need help, just ask.

I can recommend joining us on slack so it's easy for us to keep everyone updated.
We also have a twitter account: https://twitter.com/storybookjs

**Comment by mworkr** [comment]
Hey @tuchk4, We love your package and use it!  

I've forked a branch and updated it to work with 3.0.0 here: https://github.com/mworkr/storybook-readme.  It undoes some of the work of your previous updates, though mostly exposing stuff hidden behind gitignore.  

If this is something that you'd like a PR for, I'm happy to squash the commits and make a better message.  Thanks for your work on this!

**Comment by tuchk4** [comment]
Hey, sorry for late response(

I published new addon version under *next* tag.

`npm i storybook-readme@next`
![image](https://cloud.githubusercontent.com/assets/5140611/26718576/1f40596e-478a-11e7-931b-662bc8fd1774.png)

Can you please try it and if everything is OK - I will release it.

**Comment by tuchk4** [comment]
@mworkr 
> Not done enough digging--but I suspect the reason is that /register /with-readme (rather than src/register and src/with-readme) have dependencies on the old storybook but are not included in master as they are hidden behind .gitignore. I might be misunderstanding something, though.

All sources that are under *src/* dir should be commited to git.
All sources at the root - are transpiled code from *src/* dir and should NOT be commited to git but should be published to npm.

- `npm run dev` - start watchers and transpile code.
- and there is the prepubish hook (can be started manually `npm run prepublish`) - to transpile code before publishing to npm.

**Comment by mworkr** [comment]
@tuchk4 Thanks for the clarification! (I'm new to the OSS community).  That is almost certainly it, as the only changes I made were updating the dependencies in those two files.  I'll check out the new addon if I can grab some time this weekend.

**Comment by mworkr** [comment]
@tuchk4: Working off your released @next works like a charm fine for our storybook in dev.

**Comment by tuchk4** [comment]
@mworkr super cool. Will release v3 tomorrow 👍 

Thanks for feedback.

**Comment by ctumolosus** [comment]
@tuchk4 will you be releasing v3 anytime soon?

**Comment by tuchk4** [comment]
@ctumolosus published `storybook-readme@3.0.1`

**Comment by tuchk4** [comment]
Close issue. Open again if any troubles with v3
