### ISSUE TITLE
Instaled from npmjs 2.0.2 have incorrect imports

### ISSUE THREAD

**Issue by Kyr** [tuchk4/storybook-readme#22]
`import addons from '@kadira/storybook-addons';`
in both: with-readmy.js and register.js 

see https://registry.npmjs.org/storybook-readme/-/storybook-readme-2.0.2.tgz

**Comment by tuchk4** [comment]
@Kyr yeah. This is old version.
try `npm install --save react-storybook@next` and if everything is ok I will release it.

Close this because there is the issue about v3 - https://github.com/tuchk4/storybook-readme/issues/21

**Comment by Kyr** [comment]
Thanks for answer @tuchk4.
For the very first, my concern was only about incorrect version published on nmpjs, it's 2.0.2 and it's broken. At same time, latest on github 2.0.1.

I'm sure you mean `npm install --save storybook-readme@next` instead `react-storybook`.
I had try to update and it's look :ok:, no any problem with dependencies during install and all work like a charm
