### ISSUE TITLE
Theme error when using Storybook 5.3+

### ISSUE THREAD

**Issue by jayknott** [tuchk4/storybook-readme#221]
This is a follow up to issue  #220. I am having the same issue and I do not set a custom theme at all.  I had to add the following to make the error go away:

`addParameters({ options: { theme: {} } });`

**Comment by webketje** [comment]
In [packages/storybook-readme/src/services/getParameters.js#L17](https://github.com/tuchk4/storybook-readme/blob/master/packages/storybook-readme/src/services/getParameters.js#L17), should be something like 
```javascript
...(parameters.options && parameters.options.theme ? parameters.options.theme : {})
```

**Comment by bbellmyers** [comment]
This fixes issue https://github.com/tuchk4/storybook-readme/issues/228 as well

**Comment by marksy** [comment]
Thanks @bbellmyers 

FYI if you're using Typescript you need to define `base`;
`.addParameters({ options: { theme: { base: '' } } });`

**Comment by danielo515** [comment]
This is happening to me too. What is exactly the solution? I don't see any concrete example.
I am configuring my theme as it is explained on the docs of storybook. Could you please explain to me what I have to do from the normal up to date configuration?

**Comment by danielo515** [comment]
Ok, if anyone is looking for an up-to-date workaround with complete context, add this to your `preview.js` under your `.storybook` folder:

```js
import { addParameters } from '@storybook/react';

addParameters({
  options: {
    theme: {}// this is just a workaround for addon-readme
  },
})
```

**Comment by jordymeow** [comment]
If I use the code proposed by @danielo515, I get "Passed an incorrect argument to a color function, please pass a string representation of a color" instead of the previous error.

**Comment by webketje** [comment]
@jordymeow Please see [my comment above](https://github.com/tuchk4/storybook-readme/issues/221#issuecomment-586183042)
