### ISSUE TITLE
string.raw not supported on IE11

### ISSUE THREAD

**Issue by gusdaud** [tuchk4/storybook-readme#23]
Hey,

I've noticed that storybook-readme doesn't work on IE11. 

It displays a message saying that string.raw was not found.

That's because this method is used on storybook-readme but it is not supported on IE11.

Can this be fixed without us users having to add polyfills ?

**Comment by tuchk4** [comment]
@gusdaud yes, I will fix this in nearest days.

**Comment by tuchk4** [comment]
@gusdaud Sorry for late response. Please check `v3.0.2`

**Comment by blechner** [comment]
@tuchk4 thanks. But we are still using storybook 2. Could you please add this fix to the storybook-readme 2.x as well?

**Comment by tuchk4** [comment]
@blechner Check `2.0.3`

**Comment by ndelangen** [comment]
@blechner what's holding you back from upgrading? What info are you missing?

From what I've experienced and heard from other users upgrading is really simple and painless.

**Comment by blechner** [comment]
@ndelangen The upgrade from storybook 2 to 3 requires upgrades of other tools, such as webpack, and we are not doing that right now.

**Comment by blechner** [comment]
@tuchk4 by the way, `2.0.3` causes this error

![image](https://user-images.githubusercontent.com/12237934/27146121-924aaea4-510e-11e7-9c67-848c2f8c0cd7.png)

**Comment by blechner** [comment]
it worked after ran 'npm install string-raw --save' inside `node_modules/storybook-readme`, which means that it was only missing the string-raw entry in package.json.
If you could please publish 2.0.4 with this change, I would be grateful 😄

**Comment by tuchk4** [comment]
Ohh sorry

Was hard working day and I am very inattentive today :( Today I did switch from npm@5 to other versions multiple times and forgot to add `-s` flag for `npm i`

will publish new 2.0.4 a bit later today

**Comment by blechner** [comment]
Thank you very much!

**Comment by gusdaud** [comment]
Thank you so much, we really appreciate your work

**Comment by tuchk4** [comment]
published `2.0.4` with fixed `stirng-raw`
