### ISSUE TITLE
Usage with Component Story Format (CSF)

### ISSUE THREAD

**Issue by gaurav5430** [tuchk4/storybook-readme#233]
The documentation/readme does not show any examples of usage with CSF. 

I am trying to integrate this addon with storybook 5.3.18, but seeing "no README found" .

This is how i am trying to use it:

```
export default {
  title: 'Spinner',
  parameters: {
    componentSubtitle: 'Various sizes for Spinner',
    readme: {
      sidebar: SpinnerReadme,
      content: SpinnerReadme,
    },
  },
  component: Spinner,
};
```

where SpinnerReadme is a README.md loaded using raw-loader.

**Comment by joshjeong** [comment]
Did you add the following to your preview.js?

```
import { addReadme } from 'storybook-readme';

addDecorator(addReadme);
```

**Comment by gaurav5430** [comment]
> Did you add the following to your preview.js?
> 
> ```
> import { addReadme } from 'storybook-readme';
> 
> addDecorator(addReadme);
> ```

Sorry for replying late.

Yeah, that was it. Thanks :)
