### ISSUE TITLE
100% markdown support

### ISSUE THREAD

**Issue by deehuey** [tuchk4/storybook-readme#25]
Hey there! You state you have 100% markdown support, yet it appears to have issues rendering JSX, which would seem like the most common use case for a storybook UI library. Even in the image on your README.md you can see the styling doesn't appear correctly. 

Example Github Output:

``` jsx
import {
  FloatingBox,
  FloatingBoxItem,
  FloatingBoxText,
  FloatingBoxContent,
  ResetIcon,
  TrashIcon,
  Input
} from 'example';

// Example of just regular text
<FloatingBox>
  <FloatingBoxText>Hey there!</FloatingBoxText>
</FloatingBox>

// Example with some selectable items
<FloatingBox>
  <FloatingBoxItem onClick={ handleSelect } icon={<ResetIcon />}>Reset Password</FloatingBoxItem>
  <FloatingBoxItem onClick={ handleSelect } icon={<TrashIcon />}>Delete User</FloatingBoxItem>
</FloatingBox>

// Example with dynamic content

<FloatingBox>
  <FloatingBoxContent>
    <Input placeholder="Search..." search></Input>
  </FloatingBoxContent>
  <FloatingBoxItem style={{ marginTop: '10px' }} onClick={ handleReset } icon={<ResetIcon />}>Reset password</FloatingBoxItem>
  <FloatingBoxItem onClick={ handleReset } icon={<ResetIcon />}>Reset password</FloatingBoxItem>
</FloatingBox>
```

Has no issue rendering `jsx` markdown.

Yet this appears completely broken in the actual readme in storybook.

![image](https://user-images.githubusercontent.com/29404735/27845271-b5a27556-60fb-11e7-9703-8632530ca5f9.png)

**Comment by tuchk4** [comment]
highlitejs still does not support JSX in 2017  :(

switched to [prismjs](http://prismjs.com/) and published `v3.0.5`.

Check latest version and report if any problems (even if you dislike highlite theme 😄)

**Comment by ndelangen** [comment]
Yeah I'm using Prism for storybook docs v2 as well, it also let's you color syntax a bit more precise. 👍

**Comment by deehuey** [comment]
Dude! Thanks so much for fixing this up in a timely manner. It looks great now!!

Colors are not important to me!
