### ISSUE TITLE
Cannot read property 'emit' of null 

### ISSUE THREAD

**Issue by CosminIonascu** [tuchk4/storybook-readme#26]
Hi, 
I'm having this problem after upgrade to "@storybook/react": "^3.1.8":
" TypeError: Cannot read property 'emit' of null
    at emitAddReadme (with-readme.js:26)
    at with-readme.js:38
    at client_api.js:109
    at client_api.js:110
    at WrapStory.render (WrapStory.js:65)
    at ReactCompositeComponent.js:796
    at measureLifeCyclePerf (ReactCompositeComponent.js:75)
    at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (ReactCompositeComponent.js:795)
    at ReactCompositeComponentWrapper._renderValidatedComponent (ReactCompositeComponent.js:822)
    at ReactCompositeComponentWrapper.performInitialMount (ReactCompositeComponent.js:362)"
Before the update the addon was working fine

**Comment by tuchk4** [comment]
@CosminIonascu Can you provide more details so I can reproduce and fix this.

**Comment by CosminIonascu** [comment]
Sorry for the missing details, I updated react storybook to 3.1.8. and after this update I'm getting that error when I try to open a story. I'm using react + typescript+ webpack 2

**Comment by CosminIonascu** [comment]
Ok 
1.I added import 'storybook-readme/register'; in addons.js
2.In the component story 
import {action, module, storiesOf } from '@storybook/react';
import withReadme from 'storybook-readme/with-readme';
import { checkA11y } from 'storybook-addon-a11y';
import { DropDown } from '../views/DropDown';
import * as React from 'react';

const README = require('../../README.md');
storiesOf('elc-dropdown', module)
  .addDecorator(withReadme(README))
  .addDecorator(checkA11y)
  .add('Basic dropdown with 5 options with no current value', () => (
    <div style={containerStyle}>
      <DropDown options={options} onChange={onChange()} />
    </div>
  ));

I didn't change anything, I only update react storybook to 3.1.8, before this update the decorator worked fine

**Comment by tuchk4** [comment]
what storybook-readme version?

**Comment by ndelangen** [comment]
We saw this exact message over at storybook too, and it was solved by making sure all packages were correctly updated, and all installed modules and lockfiles were removed before installing.

**Comment by ls-guillaume-lambert** [comment]
I'm also getting this after updating `@storybook/react` to `3.2.0`, even with the latest `storybook-readme` at `3.0.6`.

**Comment by ls-guillaume-lambert** [comment]
Nevermind, I updated all addons I had to their latest version and it works fine :+1:
