### ISSUE TITLE
Has anyone figured out how to use this with a non-ejected create-react-app?

### ISSUE THREAD

**Issue by duro** [tuchk4/storybook-readme#29]
Due to the webpack config mod, it would seem that this needs to be done on an ejected CRA (`create-react-app`) based project. This is rather unfortunate especially since Storybook itself prides itself on working with CRA out of the box.

Any chance you know of a way to work around this?

**Comment by ndelangen** [comment]
Instead of loading in markdown, load in a js file exporting a string?

**Comment by duro** [comment]
I forgot that storybook has its own web pack config. I went ahead and added
the raw-loader there.
