### ISSUE TITLE
createClass deprecation warning

### ISSUE THREAD

**Issue by smrq** [tuchk4/storybook-readme#30]
This project uses `react-remarkable`, which uses the deprecated `React.createClass` function.  This means that this addon will not work with React 16.x.  `react-remarkable` hasn't been updated in several years, so I wouldn't expect a fix on that end.

The `@storybook/addons-info` addon uses [marksy](https://github.com/cerebral/marksy) for rendering Markdown, so perhaps that would be a viable alternative.

**Comment by duro** [comment]
Yep, I started getting this as well

**Comment by maxlapides** [comment]
another option? https://github.com/Thinkmill/react-markings

**Comment by ndelangen** [comment]
@tuchk4 Are you working on resolving this? I saw some new version coming up in slack?

**Comment by danahartweg** [comment]
It looks like `react-remarkable` was just updated to `1.1.2` a few days ago, with what looks to be removal of the deprecated React calls.

I’ll pull everything down and see if that’s actually the case / fixes up `storybook-readme`.

**Comment by tuchk4** [comment]
@danahartweg @ndelangen I prepared large update. But unfortunately I don't have enough time to  test it and release :(
Hope will do it at the end of next week.

@danahartweg `react-remarkable@1.1.2` is OK could you please send PR?

**Comment by ndelangen** [comment]
@tuchk4 Maybe you could be a little bit more liberal with access right to this repo so the others can help you more effectively? ♥️

**Comment by tuchk4** [comment]
released beta version `storybook-readme@3.1.0-beta2` without deprecation warnings.
Also added new  Apis:
- [withDocs(README)](https://github.com/tuchk4/storybook-readme#usage)
- [withDocs. addFooter(README)](https://github.com/tuchk4/storybook-readme#withdocs---common-footer)

**Comment by tuchk4** [comment]
@ndelangen I granted you permission. 

I know that you know about it.  Just keep all participants up to date (because I didn't answer on your message)

**Comment by ndelangen** [comment]
Closing this issue, looks resolved to me, please re-open if it isn't resolved 👍
