### ISSUE TITLE
Сustomizable panel name / ability to add multiple tabs

### ISSUE THREAD

**Issue by SuperOl3g** [tuchk4/storybook-readme#32]
Firstly great thanks for such useful plugin!
Secondly How about add ability to create multiple tabs with docs.
I think "README" + "CHANGELOG" is pretty frequent case.

**Comment by SuperOl3g** [comment]
I can help and do this, but I wanna know your opinion about the concept.
You may have to rename your package according to this idea 🙂

**Comment by tuchk4** [comment]
Hi,
I like this idea! But not sure if it is possible to implement (I mean dynamic panels)

Panels are registered after importing `storybook-readme/register` at `.storybook/addons.js`.

I think we can make it configurable:

```js
import register from `storybook-readme/register`

register({
  panels: ['README', 'DOCS',  'CHANGELOG']
});
```

At stories:

```js
const withChangelog =  storybookReadme.at('CHANGELOG');
const withReadme =  storybookReadme.at('README');

storiesOf('Button', module)
  .addDecorator(withChangelog(ButtonChangelog))
  .addDecorator(withReadme(ButtonReadme))
```
And we should hide panel if it is unused at active story.

**Comment by tuchk4** [comment]
@ndelangen What do you think about this?

**Comment by SuperOl3g** [comment]
Yeah, sounds good!
But AFAIU there is no possibility to hide panel if we have no content.

**Comment by tuchk4** [comment]
@SuperOl3g if it is not possible to hide panels - this feature will be not so useful.

If there is story without docs / changelog / readme / etc. - all panels will be shown and with empty content.

But we can contribute to storybook :) Suggest "Hide panels" feature

**Comment by ndelangen** [comment]
@SuperOl3g @tuchk4 I'm working on improving the extensibility of Storybook to make these things much easier. Not just to make addons hidable, I think that would be selling a faster horse.

What I'm working on is a re-implementation of the core ui layout. It would allow users to show multiple addons at once, in any split-configuration they please.

It's likely a 3.4 feature

**Comment by tuchk4** [comment]
So multiple tabs with different docs will not be useful (until it is possible to hide tab if there is no assigned doc).

@SuperOl3g Actually we can implement tabs inside main tab.

![image](https://user-images.githubusercontent.com/5140611/31508840-0513f418-af88-11e7-8f4a-8d4a479e1acc.png)

I like this feature. 

If you would like to implement it - I will be happy.  Consider that the same behaviour should be implemented for `withDocs` api.

**Comment by SuperOl3g** [comment]
@tuchk4 Sorry, I think this solution doesn't look cool enough.
@ndelangen how can I help to implement new core API feature?

**Comment by tuchk4** [comment]
This is feature is not useful until it is not possible to hide panels.
I close this issue for now.

Please reopen if you have another idea how to implement it :)

**Comment by SuperOl3g** [comment]
affirmative)

**Comment by ndelangen** [comment]
@SuperOl3g Join me on the Storybook slack and we can discuss how we can co-dev this feature.
https://now-examples-slackin-nqnzoygycp.now.sh/

I would be super happy to peer with you on this!

**Comment by ndelangen** [comment]
I've opened a PR here:
https://github.com/storybooks/storybook/pull/2101
