### ISSUE TITLE
opinionated styling of withDocs component wrapper

### ISSUE THREAD

**Issue by jptredoux** [tuchk4/storybook-readme#33]
> not a bug -- a point of discussion

Great new functionality, but I'm finding the opinionated styling (background and text-align in particular) to be a bit of a problem for me

https://github.com/tuchk4/storybook-readme/blob/master/src/with-docs.js#L18

Setting a background color here breaks the advantage of having something like `addon-backgrounds` running alongside it

(https://github.com/storybooks/addon-backgrounds)

With text-align set as center, I foresee myself having to additionally set `text-align: left` on all my components -- setting it on a component feels like it should be a solution based choice, and not due to a development tool quirk

(i.e. default browser alignment should be respected -- if a user wants everything center aligned, they should opt in to it themselves)

**Comment by tuchk4** [comment]
@jptredoux I think we can make withDocs styles configurable.  

But we need to find best way how to configure it.

**Comment by tuchk4** [comment]
will not release this feature until resolve this issue

**Comment by tuchk4** [comment]
I would like to have two approaches.

First - to set Preview component globally (as you suggested).
```js
import { withDocs } from 'storybook-readme';

// global preview component for all stories
withDocs.usePreviewComponent(({ children }) => {
  //
});
```

Second way - use *configureWithDocs* to setup *withDocs* as needed.
In this way we can setup different Preview components for different stories.
```js
import { configureWithDocs } from 'storybook-readme';

const withDocs = configureWithDocs({
  preview: ({ children }) => {
    //
  }
});
```

@jptredoux What do you think?

**Comment by jptredoux** [comment]
Sounds good 👍 

I'll have a look at creating an initial pull request for review at some point within the next day.

Another interesting option may be to curry withDocs for configuration. This would allow the implementer to set up a global (reusable) configuration themselves or apply it to a single instance.
It may add a little complexity for first time users, but the pattern is quite common.
The advantage of this is having a single entrypoint to the functionality (no split between `withDocs` and `configureWithDocs`).

```javascript
const withDocs = ({ preview }) => (readme, storyFn = null) => {
  // ...
};
```

```javascript
import { withDocs } from 'storybook-readme';

const Preview = ({ children }) => {
  // ...
};

const docsWithCustomPreview = withDocs({ preview: Preview });

storiesOf('Button', module)
  //  default docs preview view
  .addDecorator(withDocs()(ButtonDocs))
  .addWithInfo('Default', () => (
    // ...
  ));

storiesOf('Content', module)
  // custom docs preview view
  .addDecorator(docsWithCustomPreview(ContentReadme))
  .addWithInfo('Default', () => (
    // ...
  ));

storiesOf('Header', module)
  // custom docs preview view (inline)
  .addDecorator(withDocs({ preview: Preview })([HeaderReadme, HeaderAdvancedReadme]))
  .addWithInfo('Default', () => (
    // ...
  ));
```

**Comment by tuchk4** [comment]
Looks good. Lets try this way.

**Comment by jptredoux** [comment]
I've implemented the changes :

https://github.com/tuchk4/storybook-readme/compare/master...jptredoux:withdocs-configurable

or

https://github.com/tuchk4/storybook-readme/compare/master...jptredoux:withdocs-configurable-footer (including `FooterElement` for instance level `addFooter`)

Please have a look -- If you're happy with the approach I'll submit a pull request (with updated README docs)

**Comment by tuchk4** [comment]
I like idea to style footer text with component. But I don't want to push `FooterElement` to `sources` because this is just array of text(strings) in Markdown format.

```js
  if (FooterElement) {
    source.push(FooterElement);
  }
```

I suggest to implement feature in this way:

```js
const DefaultPreview = () => {
  //..
};

const DefaultFooter = () => {
  //..
};

const withDocsContainer = (
  { storyFn, kind, story, readme },
  { PreviewComponent = DefaultPreview, FooterComponent = DefaultFooter }
) => {
  // ..
  return (
    <div>
      {/* Mardown before Component Story */}
      {readmeBeforePreview &&
        <ReadmeContainer
          style={markdownContainerStyle}
          markdown={readmeBeforePreview}
        />}
      <PreviewComponent>{storyFn()}</PreviewComponent>

      {/* Mardown after Component Story */}
      <ReadmeContainer markdown={clearSplitter(fullReadmeAfterPreview)} />

      {/* Footer Mardown. Could be styled with FooterComponent */}
      {common.footer &&
        <FooterComponent>
          <ReadmeContainer markdown={common.footer} />
        </FooterComponent>}
    </div>
  );
};
```

if you are happy with this please submit PR

**Comment by jptredoux** [comment]
I will look at extending the footer as you suggested in a subsequent PR -- sounds like a good approach to me. In the meantime I have submitted the `PreviewElement` configuration changes for review

**Comment by rapgut-WittGruppe** [comment]
Is there still a way to set the Preview Element style on a global level (e.g. inside the `config.js`)?
