### ISSUE TITLE
npm package missing withDocs function

### ISSUE THREAD

**Issue by beshanoe** [tuchk4/storybook-readme#35]
After I've run `yarn add storybook-readme`, it's node_modules/storybook-readme folder is missing `with-docs.js` file, so I can't use it
![image](https://user-images.githubusercontent.com/1383547/31657748-dbdce8b2-b337-11e7-9807-a7bd8596882d.png)

**Comment by tuchk4** [comment]
This feature is still in beta at `3.1.0-beta2`

https://unpkg.com/storybook-readme@3.1.0-beta2/with-docs.js

I am going to release to stable version in next few days.

**Comment by beshanoe** [comment]
I suggest you to put updated readme to the related branch until release, cause I spent plenty of time trying to figure out what's going on here

**Comment by tuchk4** [comment]
Thank or suggestion!)
Usually we do the way you said.

But this time something went wrong
