### ISSUE TITLE
Error: Can't resolve 'storybook-readme'

### ISSUE THREAD

**Issue by bcbrian** [tuchk4/storybook-readme#36]
Webpack is unable to resolve the module.

When I go to `node_modules/storybook-readme` the `package.json` does not have a `main` key.

Manually adding this fixes the issue. It seems like it is in the current `package.json`.

Is the current build not published yet? Does the build negate that for some reason? Maybe I am just messing something up?

**Comment by andreasvirkus** [comment]
Also having this issue (with `3.0.6`)

**Comment by bcbrian** [comment]
For the time being I am importing like this.
```
import withReadme from 'storybook-readme/with-readme';
```
It seems to be working for now.

**Comment by tuchk4** [comment]
I am waiting for #34 and will release version (not beta) with all import fixes an d update docs.

Note that current `master` is not released.
