### ISSUE TITLE
Markdown: not render tables

### ISSUE THREAD

**Issue by batazor** [tuchk4/storybook-readme#4]
![screenshot from 2016-10-21 14-37-05](https://cloud.githubusercontent.com/assets/1643797/19597228/039765de-979c-11e6-9374-298d312f9462.png)

**Comment by batazor** [comment]
![screenshot from 2016-10-21 14-37-05](https://cloud.githubusercontent.com/assets/1643797/19597228/039765de-979c-11e6-9374-298d312f9462.png)

**Comment by tuchk4** [comment]
MD is rendered via https://github.com/rexxars/react-markdown 

I linked issue for tables.

If `react-markdown` contributors does not react on this and add table support - I will spawn this component with  for example:

* https://github.com/acdlite/react-remarkable

**Comment by tuchk4** [comment]
@batazor try v1.2.0

now https://github.com/acdlite/react-remarkable is using instead of https://github.com/rexxars/react-markdown

**Comment by batazor** [comment]
Yes, now it works
![screenshot from 2016-10-23 00-13-33](https://cloud.githubusercontent.com/assets/1643797/19622589/af082114-98b5-11e6-9ab9-fff3b2a2fda9.png)
