### ISSUE TITLE
Please add Typescript support

### ISSUE THREAD

**Issue by hungrysquirrel** [tuchk4/storybook-readme#40]
I am trying to use the module with Typescript and I attempted to load @types/storybook-readme but it's not available.

**Comment by ndelangen** [comment]
Hi @hungrysquirrel, thanks for the suggestion! 

Would it be possible for your to create typescript types over at the http://definitelytyped.org/ ?

**Comment by jitendravyas** [comment]
@hungrysquirrel check this discussion too if it helps https://twitter.com/chinchang457/status/951385311807913985

**Comment by tuchk4** [comment]
close because of inactivity.
