### ISSUE TITLE
Current version?

### ISSUE THREAD

**Issue by mnicole** [tuchk4/storybook-readme#42]
Hello,

I am confused about the current version of this project. It seems like the current version is 3.1.1, but the code hosted here at github is referencing 3.0.6 as the latest version. I would like to fork the project, but cannot find the latest version of the code (which is different than what is hosted here).

What I am trying to do is add an export to the DefaultPreview component. When using this library with the "Info" addon, the propTables in addon show ""DefaultPreview" Component No propTypes defined!" as well as ""ReadmeContainer" Component No propTypes defined!". As a fix, I am importing ReadmeContainer into config.js and using the option for "propTablesExclude" from the Info addon, but I cannot import "DefaultPreview", as it is not exported in the code (and I cannot find any reference to it in the currently hosted version).

Thanks!

**Comment by tuchk4** [comment]
Current master is not released.
Will release in next few days.

Since three is vue support and a lot of new feature I should update docs but have not enough time

**Comment by mnicole** [comment]
Thank you for the update!

**Comment by tuchk4** [comment]
Current master == `3.2.0`

Sorry for late response

**Comment by DrSensor** [comment]
@tuchk4 Current `master` branch support `.vue` and custom-block but in npm registry, it is not :question:
