### ISSUE TITLE
in-consistent margin for markdown texts before and after previewed component

### ISSUE THREAD

**Issue by alexQch** [tuchk4/storybook-readme#43]
Hi @tuchk4 , 
First of all, great work for build this plugin. It's very useful.
While I'm checking the online demo, I found there's a slight change of margin for the markdown texts before and after the previewed component as shown in blew:
![2017-12-04 17_29_55-storybook](https://user-images.githubusercontent.com/502551/33545515-6a69cbb6-d919-11e7-86d6-434dfdfb4957.png)

From my inspection, it seems the markdown block got a in-line style for margins and the second markdown block does not. 
![2017-12-04 17_36_03-storybook](https://user-images.githubusercontent.com/502551/33545618-b2272bb0-d919-11e7-9b99-7bc12dbce5ed.png)
Is this done on purpose?

**Comment by tuchk4** [comment]
Yeah, this is bug. Will fix in next release

**Comment by alexQch** [comment]
@tuchk4 Great!

**Comment by tuchk4** [comment]
fixed
