### ISSUE TITLE
How should I use Readme and theming together?

### ISSUE THREAD

**Issue by varya** [tuchk4/storybook-readme#44]
I'm trying to add Readmes to my Storybook. But it uses theming, and the addon give error

```
Expecting a valid React element from the story: "test" of "Button".
Seems like you are not returning a correct React element from the story.
Could you double check that?
```

This is how I write the story:

```
import React from 'react'
import { withTheme } from 'utils'
import { storiesOf } from '@storybook/react'
import ButtonReadme from './README.md'
import { withReadme, withDocs }  from 'storybook-readme';

storiesOf('Button', module)
  .add('test', withReadme(ButtonReadme, () => {
    return withTheme(() => <div>Hello world</div>)
  }))
```

**Comment by tuchk4** [comment]
Could you please show `withTheme` function

**Comment by tuchk4** [comment]
Close this issue for now. please reopen if still have problems

**Comment by varya** [comment]
Hi. You can reproduce the error in this branch: https://github.com/SC5/ds-workshop-storybook-boilerplate/tree/storybook-readme
If you run `npm start`, and when it's ready navigate to http://localhost:6005/?selectedKind=Button&selectedStory=test&full=0&down=1&left=1&panelRight=0&downPanel=REACT_STORYBOOK%2Freadme%2Fpanel you can see the error.

The `withTheme` is a function which is needed for wrapping with `ThemeProvider` https://github.com/SC5/ds-workshop-storybook-boilerplate/blob/storybook-readme/src/utils.js
The same approach is used in some other libraries, for example in Coderbox https://github.com/coderboxapp/coderbox-atoms/blob/master/src/utils.js
