### ISSUE TITLE
issue with rendering MD

### ISSUE THREAD

**Issue by JamesBliss** [tuchk4/storybook-readme#46]
Hey,

My markdown files are rendering with `module.exports = "# `.

I'm using `"storybook-readme": "^3.2.0"` and `"@storybook/react": "^3.3.6"`

and implementing it like

```
const stories = storiesOf('Avatar', module);
stories.addDecorator(withReadme(README));
```

Any idea?

**Comment by dekeey** [comment]
Got same thing today, whats your OS? Win?

**Comment by JamesBliss** [comment]
@dekeey  Latest version of macOS

**Comment by tuchk4** [comment]
refs #48

**Comment by tinkusam** [comment]
Thanks @tuchk4
