### ISSUE TITLE
Please allow Emoji's

### ISSUE THREAD

**Issue by smollweide** [tuchk4/storybook-readme#59]
Hi @tuchk4,

first of all thank you for this addon, it's really helpful 😄 

As you can see at the end of the line above emoji's are really important these days.

For Example I would like to add a changelog to storybook. To make it as easy as possible to separate the different kinds of changes I use something like this:

### :rocket: Features
which is currently rendered as sting:
<img width="238" alt="2018-05-04_1408" src="https://user-images.githubusercontent.com/2912007/39627030-95cbf85e-4fa4-11e8-936f-b1b9586e958d.png">

What do you think, is it possible?

Best,
Simon

**Comment by smollweide** [comment]
Hi @ndelangen,
I just created the [PR](https://github.com/tuchk4/storybook-readme/pull/60).

Feedback welcome 😄

**Comment by tuchk4** [comment]
Oh nice PR. thanks a lot @smollweide 

will test it and merge as soon as possible

**Comment by tuchk4** [comment]
Would like to return to this feature request and perpare it for next release.

**Comment by tuchk4** [comment]
released in `4.0.0`

**Comment by tuchk4** [comment]
the looongest feature request )) but finally at npm )

**Comment by tuchk4** [comment]
released at `4.0.0`
