### ISSUE TITLE
"README.md was not added"

### ISSUE THREAD

**Issue by kevinSuttle** [tuchk4/storybook-readme#6]
Has this been tested for Webpack 2?

**Comment by tuchk4** [comment]
@kevinSuttle yes. Everything is ok.

If you have problems could you provide more details?

**Comment by batazor** [comment]
@kevinSuttle I use webpack 2 and I have everything working well.

**Comment by yaelballa** [comment]
Hi,

I have a similar issue. I'm getting the error: 

> Module not found: Error: Cannot resolve 'file' or 'directory' ../src/components/button/README.md 

I've added the loaders config to the storybook webpack config file (.storybook/webpack.config.js). this is the content of the file:

```
module.exports = {
  plugins: [  ], 
  module: {
    loaders: [
        {
            test: /\.md$/,
            loader: "raw"
        }, {
            test: /\.json$/,
            loader: 'json'
        }, {
            test: /\.css$/,
            loader: 'style!css'
        }
    ],
  },
};
```

I also run npm install for raw-loader json-loader style-loader css-loader. Here are the versions I have:
```
    "raw-loader": "^0.5.1",
    "json-loader": "^0.5.4",
    "css-loader": "^0.23.1",
    "style-loader": "^0.13.1",
```

(I'm not using the info addon, it it matters)

Did I missed anything? can you please help?

thanks

**Comment by tuchk4** [comment]
Are sure that this file `../src/components/button/README.md` exists?
Can you please show your app structure?

**Comment by tuchk4** [comment]
`Module not found: Error: Cannot resolve 'file' or 'directory' ` 
Seems this is webpack error. And it does  not relate to this storybook or storybook addons.

Can you please show your app files structure?

**Comment by yaelballa** [comment]
it was an uppercase problem :((

sorry I will delete this issue
