### ISSUE TITLE
Navigate to particular section of READ-ME file

### ISSUE THREAD

**Issue by amittkSharma** [tuchk4/storybook-readme#62]
Hi Valerii, 

I am working on a project with Storybook, I have a situation I have a single README file documenting all controls. 

Is it possible to show a specific section of README file in the README addon section when a particular story is selected from the stories panel?

E.g. I select button from the stories panel and README panel will get updated with the button section from README file. 

Thanks in advance.
Amit

**Comment by tuchk4** [comment]
It is not possible with current api.

But you can do it your application (need to specify function that parses sections from README)

```js
import { withDocs } from 'storybook-readme';

// import single REAMDE file with all docs. 
import README from '../README.md';

const ButtonReadme = getSection('Button', README);

storiesOf('Button', module)
  .add(
    'Default',
    withDocs(ButtonReadme, () => {
      return <Button onClick={action('clicked')} label="Hello Button" />;
    })
  );
```
