### ISSUE TITLE
Suggestion: extend searching with markdown content

### ISSUE THREAD

**Issue by trevordmiller** [tuchk4/storybook-readme#70]
Would it be possible to extend the built-in storybook search input to include results from the markdown from this plugin? So that a search when using `storybook-readme` is a full storybook text search, on top of the default filtering for story names.

**Comment by tuchk4** [comment]
@ndelangen what do you think about this? As I know you are going to implement supporting of `md`  out of the box this this feature request maybe should be moved to stroybooks repo?

**Comment by tuchk4** [comment]
@ndelangen ping

**Comment by trevordmiller** [comment]
I've moved on to just using storybooks with the built-in markdown loader. I would be interested in storybook text content being searchable, but that is unrelated to this plugin. Closing.
