### ISSUE TITLE
Question: Variable driven README

### ISSUE THREAD

**Issue by bryanberger** [tuchk4/storybook-readme#71]
We currently have `less` variables defined for our Spacing system. These values are imported as `import styles from './styles.less'` for the component to use

These values are then hard-coded in a README.md and rendered using this add-on.
This obviously creates some duplication between variable definition and documentation while being brittle to change.

How would you dynamically pass style variables to be rendered in markdown?
 
Eg:

### Spacing values

| Name               | Value |
| ------------------ | ----- |
| `inset`            | '16px' |
| `inset-xxs`        | '4px' |
| `inset-xs`         | '8px' |
| `inset-sm`       | '16px' |
| `inset-md`       | '24px' |
| `inset-lg`         | '32px' |
| `inset-xl`         | '48px' |
| `inset-xxl`       | '64px' |
| `inset-xxxl`     | '72px' |

**Comment by tuchk4** [comment]
We faced the same problem and now thinking how to resolve it

**Comment by tuchk4** [comment]
Right now it is possible to pass dynamic props only in this way.
So you need to find way to get `spacing` array without hardcode. Something like to setup webpack to export variables from `less` files.

```js
import ButtonREADME from '../components/components/button/README.md';

const spacing = [{
    name: 'inset',
    value: '16px'
}, {
    name: 'inset-xxs',
    value: '4px'
}];

function injectSpacingTable(readme) {
    return `
# Spacing values

| Name | Value |
${spacing.map(({ name, value}) => {

  return `| ${name} | ${value}|
`;

})}

---

${readme}`;

}

const FinalREADME = injectSpacingTable(ButtonREADME);

storiesOf('Button', module)
  .add(
    'Default',
    withDocs(ButtonREADME, () => {
      return <Button onClick={action('clicked')} label="Hello Button" />;
    })
  );
```
