### ISSUE TITLE
Possible to hide/not include readme panel?

### ISSUE THREAD

**Issue by tomhuze** [tuchk4/storybook-readme#74]
I'm using the withDocs option to include the readmes with the story in the main panel (working great, thank you for your work on this!) But the readme tab in the add-ons panel is still over there telling me "README.md was not added." Is there any way to hide or not include the readme tab in the add-ons panel?

**Comment by trevordmiller** [comment]
Agreed, would be nice to remove the `README.md was not added` when using `withDocs` as it doesn't provide value:

![image](https://user-images.githubusercontent.com/5497885/42849139-43e706d0-89df-11e8-93b3-a3606ec9cbca.png)

**Comment by goodinmech** [comment]
"Solution" 1:

Delete the message in the panel.:

```js
import { doc, withReadme }  from 'storybook-readme';
storiesOf('Good story', module)
  .addDecorator(withReadme(" "))
  .add('Chapter title', doc(Chapter_1))
```

"Solution" 2:

Hide panel:

```js
import { configure } from '@storybook/react';
import { setOptions } from '@storybook/addon-options';

setOptions({
  showDownPanel: false,
});

// automatically import all files ending in *.stories.js
const req = require.context('../stories', true, /.stories.js$/);
function loadStories() {
  req.keys().forEach(filename => req(filename));
}

configure(loadStories, module);
```

**Comment by trevordmiller** [comment]
@goodinmech The problem with `Solution 1` is that the `README` tab still shows, even though it has nothing in it. The problem with `Solution 2` is if you are using other addons you still need the addons panel. I would instead suggest that when `withDocs` is used (instead of `withReadme`) that the `README` addons tab be hidden.

**Comment by tuchk4** [comment]
@ndelangen any news about this feature request?)

**Comment by tuchk4** [comment]
Close issue because of inactivity.

If it is still actual - open issue at storybook.

https://github.com/storybooks/storybook/issues

**Comment by evisotskiy** [comment]
Hello! I had the same question, and I have found ugly, but working way to disable readme panel. But maybe someone will come in handy, so here is it:
Create file manager-head.html in your .storybook directory and put there this code:
```
<script>
    // disable README tab
    !function hideReadmeTab() {
        if (document.body) {
            [...document.querySelectorAll('.Pane button[role="tab"]')]
                .find(tab => tab.textContent.includes('README')).style.display = 'none';
        } else {
            setTimeout(hideReadmeTab, 500)
        }
    }()
</script>
```
