### ISSUE TITLE
markdown render

### ISSUE THREAD

**Issue by darlanmendonca** [tuchk4/storybook-readme#76]
Hey guys, I'm using storybook-readme, but in my render, I receive `\n` for each break line.

How I can fix it?

<img width="809" alt="screen shot 2018-06-20 at 11 59 43" src="https://user-images.githubusercontent.com/876227/41666701-7c5ae1ee-7481-11e8-98fe-85241c377cb4.png">

**Comment by tuchk4** [comment]
@darlanmendonca show please your `package.json`

**Comment by darlanmendonca** [comment]
@tuchk4, dependencies in package.json =>

```json
{
"devDependencies": {
    "@storybook/addon-knobs": "^4.0.0-alpha.6",
    "@storybook/addons": "^4.0.0-alpha.6",
    "@storybook/react": "^4.0.0-alpha.6",
    "babel-cli": "^6.26.0",
    "babel-core": "^6.26.0",
    "babel-preset-import-export": "^1.0.2",
    "babel-preset-react": "^6.24.1",
    "babel-runtime": "^6.26.0",
    "chai": "^4.1.2",
    "chai-dom": "^1.7.0",
    "chai-enzyme": "^1.0.0-beta.0",
    "chai-spies": "^1.0.0",
    "css-loader": "^0.28.11",
    "document-register-element": "^1.7.2",
    "enzyme": "^3.3.0",
    "enzyme-adapter-react-16": "^1.1.1",
    "eslint": "^4.19.1",
    "html-loader": "^0.5.5",
    "jest": "^22.4.3",
    "jest-css-modules": "^1.1.0",
    "jsdom": "^11.6.2",
    "markdown-loader": "^3.0.0",
    "mutation-observer": "^1.0.3",
    "node-sass": "^4.8.3",
    "sass-loader": "^6.0.7",
    "storybook-addon-jsx": "^5.3.0",
    "storybook-readme": "^3.3.0",
    "style-loader": "^0.20.3",
    "webpack": "^4.8.3"
  }
}
```

**Comment by Jetsly** [comment]
```
  storybookBaseConfig.module.rules.push({
    test: /\.md$/,
    loaders: ["markdown-loader"],
    include: path.resolve(__dirname, "../test")
  });
```
you must remove html-loader,i fix it
@darlanmendonca

**Comment by tuchk4** [comment]
Yes the problem is in loaders. 
Right now I have no time to reproduce  it with you deps. versions.

@darlanmendonca do you have custom webpack config at your storybook?

**Comment by darlanmendonca** [comment]
thanks @Jetsly and @tuchk4, remove the html-loader fix the problem :D

**Comment by darlanmendonca** [comment]
but, why `html-loader` is necessary? they are in readme docs/example from storybook-readme

**Comment by JimmyLv** [comment]
![image](https://user-images.githubusercontent.com/4997466/41764378-7be4a2b4-7633-11e8-9bf6-fc4898d0393d.png)

Also have the `module.exports = "`...

**Comment by darlanmendonca** [comment]
yep @JimmyLv, but removing html loader, fix it too

**Comment by tuchk4** [comment]
@darlanmendonca 

https://github.com/tuchk4/storybook-readme#webpack-configuration-for-react-storybook

The example for versions lower than `@storybooks/storybook@3.3.0`.
Now these loaders are inside storybook core.

**Comment by Peatechen** [comment]
@Jetsly Nice
