### ISSUE TITLE
Storybook Readme Appearing in Every Addon Panel with Webpack 4 & Storybook Alpha 4.20 upgrade

### ISSUE THREAD

**Issue by lcaroselli** [tuchk4/storybook-readme#86]
The Storybook Readme addon is appearing in every addon panel after upgrading to Webpack 4 and updating Storybook to the latest Alpha release per [their recommendations here](https://github.com/storybooks/storybook/issues/3044).

[Here is a clean repository with code reproducing the error](https://github.com/lcaroselli/test-storybook-readme).

And a small gif and picture showing the error:
![](https://media.giphy.com/media/4WETZzioj1g6uXh1kQ/giphy.gif)
![screen shot 2018-09-06 at 5 04 18 pm](https://user-images.githubusercontent.com/22547367/45189574-ebbe7980-b1f6-11e8-827a-9c73774bba16.png)

This is preventing us from using the storybook readme addon after upgrading to Webpack 4 and Storybook Alpha (which is needed with the Webpack 4 upgrade). 
For clarity, we tried storybook-readme with both the @3.3.0 and @4.0.0-beta1 version. Neither one worked as expected.

**Comment by tuchk4** [comment]
Going to investigate the problem today.

**Comment by tuchk4** [comment]
will fix in next releast

**Comment by enwin** [comment]
Sorry for being impatient but is there an ETA for the next release containing this fix?

Cheers!

**Comment by tuchk4** [comment]
Going to release during next few days

**Comment by tuchk4** [comment]
released in `4.0.0`
