### ISSUE TITLE
Markdown Task List

### ISSUE THREAD

**Issue by chemoish** [tuchk4/storybook-readme#89]
Hello, I was wondering if this package supports task lists?

It looks like `marked` supports it, but when using `doc(README)` brackets get rendered instead.

Expected:

- [x] I am a task 

Actual:

-&nbsp;[ ] I am not a task

Preview:

<img width="214" alt="screen shot 2018-09-12 at 7 02 45 pm" src="https://user-images.githubusercontent.com/549319/45462852-85d26600-b6be-11e8-9942-d7b5e3524af1.png">

**Comment by tuchk4** [comment]
Here is example https://tuchk4.github.io/storybook-readme/?selectedKind=Custom%20Preview%20and%20Footer&selectedStory=Button&full=0&addons=1&stories=1&panelRight=1&addonPanel=storybooks%2Fstorybook-addon-knobs

**Comment by chemoish** [comment]
Thanks for the response. I'm not sure if it's related, but after upgrading to storybook@4 I see them fine. Anyways 🎉
