### ISSUE TITLE
Why is `@kadira/storybook-addons` peer dependency?

### ISSUE THREAD

**Issue by faddee** [tuchk4/storybook-readme#9]
When installing with Yarn I get this warning:

`warning "storybook-readme@1.2.0" has unmet peer dependency "@kadira/storybook-addons@^1.5.0".`

It's a dependency for `@kadira/storybook` but I was able to get it to work just fine without using `@kadira/storybook-addons` explicitly. So is it really necessary to have is as a peer dependency?

**Comment by tuchk4** [comment]
I took one of existing storybook addong as the example. And `@kadira/storybook-addons` at most of other addons:
- [storybook-addon-links](https://github.com/storybooks/storybook-addon-links/blob/master/package.json#L37)
- [storybook-addon-actions](https://github.com/storybooks/storybook-addon-actions/blob/master/package.json#L42)
- [storybook-addon-knobs](https://github.com/storybooks/storybook-addon-knobs/blob/master/package.json#L55)

When should you use peer dependencies?
- When you are building a library to be used by other projects, and
- This library is using some other library, and
- You expect/need the user to work with that other library as well

More info here:
- [Peer Dependencies @ nodejs.org](https://nodejs.org/en/blog/npm/peer-dependencies/)
- [Why use peer dependencies in npm for plugins?](http://stackoverflow.com/questions/26737819/why-use-peer-dependencies-in-npm-for-plugins)

I never faced such problem at all my apps with storybook and this addon. 
Can you show please your `package.json` and `npm -v`?

**Comment by faddee** [comment]
> You expect/need the user to work with that other library as well

Which I don't. I'm not expected to use `@kadira/storybook-addons` to get this addon to work and therefor would I rather not to have it as dependency at all. I was generally just wondering if I missed something. But I guess it's there for another reason.

**Comment by tuchk4** [comment]
@faddee `@kadira/storybook-addons` is dependecy of `@kadira/storybook` ([package.json](https://github.com/storybooks/react-storybook/blob/master/package.json#L28)).

Seems your get warning because of versions mismatch. That is why I asked to show your `package.json`

Or try to update all to latest versions with [npm-check](https://www.npmjs.com/package/npm-check)

```
npm-check -u
```

**Comment by faddee** [comment]
Here's my dependencies...

```json
{
  "dependencies": {
    "@types/react": "^15.0.6",
    "@types/react-dom": "^0.14.22",
    "@types/react-redux": "^4.4.36",
    "react": "^15.4.2",
    "react-dom": "^15.4.2",
    "react-redux": "^5.0.2",
    "redux": "^3.6.0",
    "ts-node": "^2.0.0",
    "tslint": "^4.4.2",
    "typescript": "2.1.5"
  },
  "devDependencies": {
    "@kadira/storybook": "^2.35.3",
    "awesome-typescript-loader": "^3.0.0-beta.18",
    "css-loader": "^0.26.1",
    "file-loader": "^0.10.0",
    "json-loader": "^0.5.4",
    "node-sass": "^4.5.0",
    "raw-loader": "^0.5.1",
    "react-svg-loader": "^1.1.1",
    "sass-loader": "^4.1.1",
    "storybook-readme": "^1.2.0",
    "style-loader": "^0.13.1",
    "webpack": "1.x"
  }
}
```
