### ISSUE TITLE
Storybook ReadMe Alpha 4 Rendering issue.

### ISSUE THREAD

**Issue by hindsc52** [tuchk4/storybook-readme#90]
I am using the latest Alpha of both storybook and storybook readme. I have had to add the custom webpack config for the html and markdown loaders (didn't think this was needed for storybook 3.3.3 and above.)

Also seeing a rendering issue when adding the markdown readme to story view.

![image](https://user-images.githubusercontent.com/14273378/45875460-a621b500-bd8f-11e8-88bb-6482a2cad457.png)

**Comment by paulomfr** [comment]
@hindsc52 
I think that your solution is [here](https://github.com/tuchk4/storybook-readme/issues/46).

**Comment by tuchk4** [comment]
@hindsc52 please try `4.0.0` and reopen issue if problem is still exist.
