### ISSUE TITLE
Custom the <StoryPreview /> component's style

### ISSUE THREAD

**Issue by beyondghx** [tuchk4/storybook-readme#91]
Sometimes we want to custom the <StoryPreview /> component's style by myself.But now, I have no way to do this.Would you add this option to change the style?

By the way, I know you're using the Prismjs to highlight the code.I think if we can change the code theme would be better.

**Comment by beyondghx** [comment]
Oh, I'm sorry...The `config.PreviewComponent` option can change the style.So the first question will be right.How about the second one : )

**Comment by tuchk4** [comment]
@beyondghx just import PrismJS theme CSS file. It should override theme from storybook-readme.

https://github.com/PrismJS/prism-themes

**Comment by tuchk4** [comment]
btw sorry for long reply :(
