### ISSUE TITLE
Suggestion: Adding types to DefinitelyTyped

### ISSUE THREAD

**Issue by lonyele** [tuchk4/storybook-readme#93]
Hi, I've been recently using storybook and found this addon. I found that there is not type definition file at DefinitelyTyped. It was ok with just making folders and "declare module", but I tried making one for myself and the community. This is my first time making it, so there should be something missing or wrong. It would be really nice if someone could help.

**Comment by lonyele** [comment]
DefinitelyTyped/DefinitelyTyped#29512
Here is the PR that I made to the DefinitelyTyped repo. I tried my best to analyze the code and mimic others d.ts...

**Comment by lonyele** [comment]
PR merged...

**Comment by tuchk4** [comment]
<3

**Comment by tuchk4** [comment]
@lonyele  sorry for long reply, had a lot of work.
Want to say a lot of thank to you for that PR.

Right now we are switching to TypeScript and your PR with types helps a lot. Thanks :)

**Comment by tuchk4** [comment]
Especially because current addon's interfaces is not perfect for typing...

Functions (withReadme / withDocs) accepts different types and different number of arguments and depends on that return different result... ))

**Comment by lonyele** [comment]
Yeah, that's true. I think types at DefinitelyType is an easier version. I looked up all codes except vue.js part, It seems like It will take some time switching all of it to fully support Typescript
