### ISSUE TITLE
Readme tab not showing in panel

### ISSUE THREAD

**Issue by EmericW** [tuchk4/storybook-readme#94]
Im trying to use the withReadme function but the tab is not showing up in the panel.

Versions:
    "@storybook/react": "^3.3.6",
    "storybook-readme": "^3.3.0",

code:
```
storiesOf('Form', module)
    .add(
        'Simple form',
        withReadme(config1Doc, () => (
            <Wrapped>
                <FormContainer handleSubmit={action('Form submitted')} config={config1} />
            </Wrapped>
        ))
    )
```
There is also nothing in my webpack config because the storybook-readme version is 3.3.0.
I also double checked that i'm importing the register in addon.js.
The withDocs function does work but i would prefer the withReadme version.

Any help would be appreciated.

**Comment by ndelangen** [comment]
Have you registered it in `addons.js`?

https://github.com/tuchk4/storybook-readme#usage

**Comment by EmericW** [comment]
Yes, i mentioned that in my question.

**Comment by tuchk4** [comment]
The strangest thing that `withDocs` works but `withReadme` not.
First time hear about such problem.

I need more details to find a problem.
Would be nice if you create repo with problem example

**Comment by EmericW** [comment]
The issue occurred on a private repository. while recreating the issue on a new public repository it started working. No idea what actually caused it. Closing this now.
