### ISSUE TITLE
version 4.0.0 has an err in register.js render fun

### ISSUE THREAD

**Issue by wanyicss** [tuchk4/storybook-readme#96]
version 4.0.0 has an err in register.js render fun:
```
can't read property 'active' of undefined
```
while version 4.0.0-beta1 is ok.
the above err occurred in @storybook/ui version 3.4.11 : AddonPanel.renderPanels()->panel.render()

**Comment by wanyicss** [comment]
> Whats version of @storybook?

3.4.11

**Comment by filippoitaliano** [comment]
I have the same problem updating from `4.0.0-beta1` to `4.0.1`!

```
 "dependencies": {
    "@storybook/addon-actions": "3.4.11",
    "@storybook/addon-options": "3.4.11",
    "@storybook/addons": "3.4.11",
    "@storybook/react": "3.4.11",
    "storybook-readme": "4.0.1",
    ...
  },
```
Error:
> TypeError: _ref is undefined (register.js:25)

**Comment by tuchk4** [comment]
Got it. Will publish fix in few hours

**Comment by tuchk4** [comment]
Please try `4.0.2`
Should be fixed.

The problem was with compatibility with storybook@3.x

**Comment by wanyicss** [comment]
4.0.2 is ok ~  thanks!
