### ISSUE TITLE
el is not defined

### ISSUE THREAD

**Issue by Tomekmularczyk** [tuchk4/storybook-readme#97]
V4.0.0

> Marked.js:62 Uncaught ReferenceError: el is not defined
>     at Marked.componentDidUpdate (Marked.js:62)
>     at commitLifeCycles (react-dom.development.js:14693)
>     at commitAllLifeCycles (react-dom.development.js:15905)
>     at HTMLUnknownElement.callCallback (react-dom.development.js:145)
>     at Object.invokeGuardedCallbackDev (react-dom.development.js:195)
>     at invokeGuardedCallback (react-dom.development.js:248)
>     at commitRoot (react-dom.development.js:16075)
>     at completeRoot (react-dom.development.js:17463)
>     at performWorkOnRoot (react-dom.development.js:17391)
>     at performWork (react-dom.development.js:17295)

<img width="371" alt="zrzut ekranu 2018-10-17 o 12 12 27" src="https://user-images.githubusercontent.com/12544704/47079552-16dcb580-d206-11e8-905c-85c39f2e9577.png">

It happens when I switch pages, but if I reload page it works.

**Comment by tuchk4** [comment]
fixed in `4.0.1`

**Comment by Tomekmularczyk** [comment]
Wow, that was super quick, thanks!
