### ISSUE TITLE
Readme displayed in knobs and action logger panels

### ISSUE THREAD

**Issue by helabenkhalfallah** [tuchk4/storybook-readme#98]
Hi, 
I have the Readme displayed even in "knobs" and "action logger" panels like showed below : 

![image](https://user-images.githubusercontent.com/1331451/47086999-d33c7880-d212-11e8-89dc-f064bc942f52.png)

![image](https://user-images.githubusercontent.com/1331451/47087017-da638680-d212-11e8-834e-64a0ca50deeb.png)

Is this a configuration error ? have I missed up a step ?
[My Project](https://github.com/helabenkhalfallah/news_kit_frontend/tree/master/app-core/ui-api-lib/ui-api-storybook)

Thanks :)

**Comment by tuchk4** [comment]
try version `4.0.1`

**Comment by helabenkhalfallah** [comment]
Thank you this resolve my issue 👍
