### ISSUE TITLE
Readme is added in each addon-panel

### ISSUE THREAD

**Issue by ravecat** [tuchk4/storybook-readme#99]
Hello!

Thank you for work!

Versions
```json
"@storybook/addon-knobs": "^3.4.10",
"@storybook/react": "^4.0.0-alpha.25",
"storybook-readme": "^4.0.0-beta1",
```

Faced with strange behaviour. Added in the config `storybook-readme` to `addons.js`
```javascript
import '@storybook/addon-actions/register';
import '@storybook/addon-knobs/register';
import '@storybook/addon-options/register';
import 'storybook-readme/register';
```

My `config.js`

```javascript
import { configure, addDecorator } from '@storybook/react';
import { withInfo } from '@storybook/addon-info';
import { withKnobs } from '@storybook/addon-knobs';
import { setOptions } from '@storybook/addon-options';
import '../src/index.scss';

const req = require.context('../src', true, /\.story\.js$/);

function loadStories() {
  req.keys().forEach(filename => req(filename));
}

addDecorator(withKnobs);
addDecorator(withInfo);

setOptions({
  addonPanelInRight: true,
});

configure(loadStories, module);

```
Example component
```javascript
import React from 'react';
import { addDecorator, storiesOf } from '@storybook/react';
import { action } from '@storybook/addon-actions';
import { text, select, boolean } from '@storybook/addon-knobs';
import { withReadme } from 'storybook-readme';
import Button from './index';
import readme from './README.md';

storiesOf('Updated Button', module).add(
  'Default',
  withReadme(readme, () => (
    <Button
      stretch={boolean('stretch', false)}
      component={text('component', 'button')}
      size={select('size', SIZES, SIZES[0])}
      outlined={boolean('outlined', false)}
      variant={select('variant', VARIANTS, VARIANTS[0])}
      onClick={action('clicked')}
    >
      {text('value', 'Button')}
    </Button>
  ))
);
```

And I see that `storybook-readme` entered in the wrong tab (for all addon-tabs except `action-logger`)

![example1](https://user-images.githubusercontent.com/24782863/47379544-dc8e7f00-d703-11e8-8679-acae48ff476d.png)
![example2](https://user-images.githubusercontent.com/24782863/47379556-e44e2380-d703-11e8-9107-7a4bdc09ce81.png)

**Comment by tuchk4** [comment]
Try stroybook readme addon ‘4.0.2’ 
Seems problem on old version. This bug already fixed

**Comment by ravecat** [comment]
Updated. Current view
![exmp3](https://user-images.githubusercontent.com/24782863/47456761-074d0600-d7de-11e8-86e4-787e46b8e8aa.png)
![exmp4](https://user-images.githubusercontent.com/24782863/47456766-0916c980-d7de-11e8-829b-cbb282944b4a.png)

**Comment by tuchk4** [comment]
Yes, exactly.
Addons registration api was changed in lastest storybook version so all deps should be update.
As I know, version of `@storybook/addon-knobs` should equal `@storybook/react` version. :)
